Feature: Export a workspace to browsable Markdown
  As a maintainer wiring architecture docs into a repository
  I want each project rendered as a README in its own folder
  so that browsing that folder on GitHub shows the architecture, diagrams and all

  Background:
    Given a LikeC4 workspace

  Scenario: Each project is rendered in its own folder by default
    Given the workspace contains more than one project
    When I export the workspace to Markdown
    Then each project gets a README page written into its own project folder

  Scenario: A project that renders to no views is skipped
    Given the workspace contains a project with no views
    When I export the workspace to Markdown
    Then no page is written for that project

  Scenario: Restricting the export to a single project
    Given the workspace contains more than one project
    When I export the workspace to Markdown for a single named project
    Then only that project gets a README page
    And the other projects are left out

  Scenario: An unknown project name is reported
    When I export the workspace to Markdown for a project that does not exist
    Then the export fails
    And it tells me the project was not found

  Scenario: Each page is the rendered architecture of its project
    When I export the workspace to Markdown
    Then each README is the Markdown rendering of its project, diagrams included

  Scenario: A configured project description carries through to the page
    Given a project with a configured description
    When I export the workspace to Markdown
    Then that README shows the description as the project overview

  Scenario: A generated page identifies itself as generated
    When I export the workspace to Markdown
    Then each README carries a marker identifying it as generated by this command

  Scenario: Regenerating a previously generated page
    Given a project folder whose README was written by a previous export
    When I export the workspace to Markdown
    Then that README is overwritten with the newly rendered architecture

  Scenario: A hand-authored README is protected from being overwritten
    Given a project folder with a README that was not generated by this command
    When I export the workspace to Markdown
    Then that project is left out
    And I am told to pass an explicit option to overwrite it

  Scenario: A README that cannot be checked is not silently treated as safe to overwrite
    Given a project folder with a README that exists but cannot be read
    When I export the workspace to Markdown
    Then the export fails
    And no file is overwritten for that project

  Scenario: Forcing an overwrite of a hand-authored README
    Given a project folder with a README that was not generated by this command
    When I export the workspace to Markdown with the overwrite option
    Then that README is overwritten with the newly rendered architecture
