/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmbedViewIdImport } from './routes/embed.$viewId'
import { Route as ExportViewIdImport } from './routes/export.$viewId'
import { Route as IndexImport } from './routes/index'
import { Route as ViewViewIdImport } from './routes/view.$viewId'
import { Route as ViewViewIdD2Import } from './routes/view.$viewId.d2'
import { Route as ViewViewIdDotImport } from './routes/view.$viewId.dot'
import { Route as ViewViewIdEditorImport } from './routes/view.$viewId.editor'
import { Route as ViewViewIdMmdImport } from './routes/view.$viewId.mmd'
import { Route as ViewViewIdReactImport } from './routes/view.$viewId.react'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const ViewViewIdRoute = ViewViewIdImport.update({
  path: '/view/$viewId',
  getParentRoute: () => rootRoute
} as any)

const ExportViewIdRoute = ExportViewIdImport.update({
  path: '/export/$viewId',
  getParentRoute: () => rootRoute
} as any)

const EmbedViewIdRoute = EmbedViewIdImport.update({
  path: '/embed/$viewId',
  getParentRoute: () => rootRoute
} as any)

const ViewViewIdReactRoute = ViewViewIdReactImport.update({
  path: '/react',
  getParentRoute: () => ViewViewIdRoute
} as any)

const ViewViewIdMmdRoute = ViewViewIdMmdImport.update({
  path: '/mmd',
  getParentRoute: () => ViewViewIdRoute
} as any)

const ViewViewIdEditorRoute = ViewViewIdEditorImport.update({
  path: '/editor',
  getParentRoute: () => ViewViewIdRoute
} as any)

const ViewViewIdDotRoute = ViewViewIdDotImport.update({
  path: '/dot',
  getParentRoute: () => ViewViewIdRoute
} as any)

const ViewViewIdD2Route = ViewViewIdD2Import.update({
  path: '/d2',
  getParentRoute: () => ViewViewIdRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/embed/$viewId': {
      preLoaderRoute: typeof EmbedViewIdImport
      parentRoute: typeof rootRoute
    }
    '/export/$viewId': {
      preLoaderRoute: typeof ExportViewIdImport
      parentRoute: typeof rootRoute
    }
    '/view/$viewId': {
      preLoaderRoute: typeof ViewViewIdImport
      parentRoute: typeof rootRoute
    }
    '/view/$viewId/d2': {
      preLoaderRoute: typeof ViewViewIdD2Import
      parentRoute: typeof ViewViewIdImport
    }
    '/view/$viewId/dot': {
      preLoaderRoute: typeof ViewViewIdDotImport
      parentRoute: typeof ViewViewIdImport
    }
    '/view/$viewId/editor': {
      preLoaderRoute: typeof ViewViewIdEditorImport
      parentRoute: typeof ViewViewIdImport
    }
    '/view/$viewId/mmd': {
      preLoaderRoute: typeof ViewViewIdMmdImport
      parentRoute: typeof ViewViewIdImport
    }
    '/view/$viewId/react': {
      preLoaderRoute: typeof ViewViewIdReactImport
      parentRoute: typeof ViewViewIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  EmbedViewIdRoute,
  ExportViewIdRoute,
  ViewViewIdRoute.addChildren([
    ViewViewIdD2Route,
    ViewViewIdDotRoute,
    ViewViewIdEditorRoute,
    ViewViewIdMmdRoute,
    ViewViewIdReactRoute
  ])
])

/* prettier-ignore-end */
