export const xynodes = [
  {
    id: 'in-customer',

    deletable: false,
    position: { x: 0, y: 223 },
    zIndex: 6,
    style: {
      width: 340,
      height: 190,
    },
    hidden: false,
    type: 'element',
    data: {
      id: 'in-customer',
      parent: null,
      position: [0, 223],
      title: 'Cloud Customer',
      description: 'The regular customer of the system',
      technology: null,
      tags: null,
      links: null,
      color: 'primary',
      shape: 'person',
      modelRef: 'customer',
      kind: 'actor',
      level: 0,
      labelBBox: { x: 0, y: 223, width: 340, height: 190 },
      style: {},
      navigateTo: 'customer',
      inEdges: [],
      outEdges: [],
      children: [],
      width: 340,
      height: 190,
    },
  },
  {
    id: 'subject-cloud.ui',

    deletable: false,
    position: { x: 610, y: 17 },
    zIndex: 2,
    style: {
      width: 400,
      height: 584,
    },
    hidden: false,
    type: 'compound',
    data: {
      id: 'subject-cloud.ui',
      parent: null,
      position: [610, 17],
      title: 'Frontend',
      description: 'All the frontend applications\nof the cloud system',
      technology: null,
      tags: null,
      links: null,
      color: 'primary',
      shape: 'browser',
      modelRef: 'cloud.ui',
      kind: 'container',
      level: 0,
      labelBBox: { x: 610, y: 17, width: 400, height: 584 },
      style: { opacity: 65, border: 'none' },
      navigateTo: 'cloud_ui',
      inEdges: [],
      outEdges: [],
      depth: 1,
      children: ['subject-cloud.ui.mobile', 'subject-cloud.ui.dashboard'],
      width: 400,
      height: 584,
    },
    dragHandle: '.likec4-compound-title',
  },
  {
    id: 'out-cloud.backend',

    deletable: false,
    position: { x: 1250, y: 17 },
    zIndex: 2,
    style: {
      width: 400,
      height: 272,
    },
    hidden: false,
    type: 'compound',
    data: {
      id: 'out-cloud.backend',
      parent: null,
      position: [1250, 17],
      title: 'Backend',
      description: 'The backend services of the cloud system',
      technology: null,
      tags: null,
      links: null,
      color: 'primary',
      shape: 'rectangle',
      modelRef: 'cloud.backend',
      kind: 'container',
      level: 0,
      labelBBox: { x: 1250, y: 17, width: 400, height: 272 },
      style: {
        opacity: 25,
        border: 'dotted',
      },
      navigateTo: 'cloud_backend',
      inEdges: [],
      outEdges: [],
      depth: 1,
      children: ['out-cloud.backend.graphql'],
      width: 400,
      height: 272,
    },
    dragHandle: '.likec4-compound-title',
  },
  {
    id: 'out-amazon',

    deletable: false,
    position: { x: 1250, y: 329 },
    zIndex: 2,
    style: {
      width: 400,
      height: 497,
    },
    hidden: false,
    type: 'compound',
    data: {
      id: 'out-amazon',
      parent: null,
      position: [1250, 329],
      title: 'Amazon Web Services',
      description: 'Cloud Infrastructure, Hosting\nand Managed Services',
      technology: null,
      tags: null,
      links: null,
      color: 'amber',
      shape: 'rectangle',
      modelRef: 'amazon',
      kind: 'externalSystem',
      level: 0,
      labelBBox: { x: 1250, y: 329, width: 400, height: 497 },
      style: { opacity: 25 },
      navigateTo: 'amazon',
      inEdges: [],
      outEdges: [],
      depth: 1,
      children: ['out-amazon.kinesis.hits', 'out-amazon.cognito'],
      width: 400,
      height: 497,
    },
    dragHandle: '.likec4-compound-title',
  },
  {
    id: 'subject-cloud.ui.mobile',

    deletable: false,
    position: { x: 30, y: 50 },
    zIndex: 6,
    style: {
      width: 340,
      height: 190,
    },
    hidden: false,
    parentId: 'subject-cloud.ui',
    type: 'element',
    data: {
      id: 'subject-cloud.ui.mobile',
      parent: 'subject-cloud.ui',
      position: [640, 67],
      title: 'Mobile App',
      description: 'The mobile app of the cloud system',
      technology: null,
      tags: null,
      links: null,
      color: 'primary',
      shape: 'mobile',
      modelRef: 'cloud.ui.mobile',
      kind: 'mobile',
      level: 1,
      labelBBox: { x: 640, y: 67, width: 340, height: 190 },
      style: {},
      navigateTo: null,
      inEdges: [],
      outEdges: [],
      children: [],
      width: 340,
      height: 190,
    },
  },
  {
    id: 'subject-cloud.ui.dashboard',

    deletable: false,
    position: { x: 30, y: 362 },
    zIndex: 6,
    style: {
      width: 340,
      height: 190,
    },
    hidden: false,
    parentId: 'subject-cloud.ui',
    type: 'element',
    data: {
      id: 'subject-cloud.ui.dashboard',
      parent: 'subject-cloud.ui',
      position: [640, 379],
      title: 'Customer Dashboard',
      description: 'Web application, that allows customers to interact with the cloud system',
      technology: 'Nextjs',
      tags: null,
      links: null,
      color: 'primary',
      shape: 'browser',
      modelRef: 'cloud.ui.dashboard',
      kind: 'app',
      level: 1,
      labelBBox: { x: 640, y: 379, width: 340, height: 190 },
      style: {},
      navigateTo: null,
      inEdges: [],
      outEdges: [],
      children: [],
      width: 340,
      height: 190,
    },
  },
  {
    id: 'out-cloud.backend.graphql',

    deletable: false,
    position: { x: 30, y: 50 },
    zIndex: 6,
    style: {
      width: 340,
      height: 190,
    },
    hidden: false,
    parentId: 'out-cloud.backend',
    type: 'element',
    data: {
      id: 'out-cloud.backend.graphql',
      parent: 'out-cloud.backend',
      position: [1280, 67],
      title: 'GraphQL',
      description: 'The GraphQL API to access data',
      technology: 'nodejs',
      tags: null,
      links: null,
      color: 'primary',
      shape: 'rectangle',
      modelRef: 'cloud.backend.graphql',
      kind: 'app',
      level: 1,
      labelBBox: { x: 1280, y: 67, width: 340, height: 190 },
      style: {},
      navigateTo: null,
      inEdges: [],
      outEdges: [],
      children: [],
      width: 340,
      height: 190,
    },
  },
  {
    id: 'out-amazon.kinesis.hits',

    deletable: false,
    position: { x: 30, y: 50 },
    zIndex: 6,
    width: 340,
    height: 190,
    hidden: false,
    parentId: 'out-amazon',
    type: 'element',
    data: {
      id: 'out-amazon.kinesis.hits',
      parent: 'out-amazon',
      position: [1280, 379],
      title: 'Hits',
      description: 'Stream of page hits from Dashboard app.\n' +
        'Data is sent via GoogleTagManager',
      technology: null,
      tags: null,
      links: null,
      color: 'amber',
      shape: 'queue',
      modelRef: 'amazon.kinesis.hits',
      kind: 'stream',
      level: 1,
      labelBBox: { x: 1280, y: 379, width: 340, height: 190 },
      style: {},
      navigateTo: null,
      inEdges: [],
      outEdges: [],
      children: [],
      width: 340,
      height: 190,
    },
  },
  {
    id: 'out-amazon.cognito',

    deletable: false,
    position: { x: 30, y: 275 },
    zIndex: 6,
    width: 340,
    height: 190,
    hidden: false,
    parentId: 'out-amazon',
    type: 'element',
    data: {
      id: 'out-amazon.cognito',
      parent: 'out-amazon',
      position: [1280, 604],
      title: 'Cognito',
      description: 'User management and authentication',
      technology: null,
      tags: null,
      links: null,
      color: 'primary',
      shape: 'rectangle',
      modelRef: 'amazon.cognito',
      kind: 'component',
      level: 1,
      labelBBox: { x: 1280, y: 604, width: 340, height: 190 },
      style: {},
      navigateTo: 'amazon_cognito',
      inEdges: [],
      outEdges: [],
      children: [],
      width: 340,
      height: 190,
    },
  },
]
