import type { Any, AnyAux } from '../types';
import { type DeploymentElementModel, DeployedInstanceModel, DeploymentNodeModel, DeploymentRelationModel, NestedElementOfDeployedInstanceModel } from './DeploymentElementModel';
import { ElementModel } from './ElementModel';
import { type AnyRelationshipModel, RelationshipModel } from './RelationModel';
import { EdgeModel } from './view/EdgeModel';
import { LikeC4ViewModel } from './view/LikeC4ViewModel';
import { NodeModel } from './view/NodeModel';
type AnyModel<A extends AnyAux> = DeploymentNodeModel<A> | DeployedInstanceModel<A> | DeploymentRelationModel<A> | AnyRelationshipModel<A> | NestedElementOfDeployedInstanceModel<A> | ElementModel<A> | RelationshipModel<A> | LikeC4ViewModel<A> | NodeModel<A> | EdgeModel<A>;
export declare function isDeploymentNodeModel<M extends AnyAux>(model: AnyModel<M>): model is DeploymentNodeModel<M>;
export declare function isDeployedInstanceModel<M extends AnyAux>(model: AnyModel<M>): model is DeployedInstanceModel<M>;
export declare function isDeploymentElementModel<M extends AnyAux>(model: AnyModel<M>): model is DeploymentElementModel<M>;
export declare function isNestedElementOfDeployedInstanceModel<M extends AnyAux>(model: AnyModel<M>): model is NestedElementOfDeployedInstanceModel<M>;
export declare function isDeploymentRelationModel<M extends AnyAux>(x: AnyModel<M>): x is DeploymentRelationModel<M>;
export declare function isRelationModel<M extends AnyAux>(x: AnyModel<M>): x is RelationshipModel<M>;
export { isRelationModel as isModelRelation, isRelationModel as isRelationshipModel, };
export declare function isElementModel<M extends Any>(element: AnyModel<M>): element is ElementModel<M>;
export declare function isLikeC4ViewModel<M extends Any>(view: AnyModel<M>): view is LikeC4ViewModel<M>;
export declare function isNodeModel<M extends Any>(node: AnyModel<M>): node is NodeModel<M>;
export declare function isEdgeModel<M extends Any>(edge: AnyModel<M>): edge is EdgeModel<M>;
