compressionLevel: mixed

enableGlobalCache: false
enableInlineBuilds: true
enableHardenedMode: false
enableTelemetry: false
tsEnableAutoTypes: true

nmMode: hardlinks-local
nodeLinker: node-modules

npmAuthToken: '${NPM_AUTH_TOKEN:-}'

npmPublishAccess: public

npmScopes:
  likec4:
    npmAuthToken: '${NPM_AUTH_TOKEN:-}'
    npmPublishRegistry: 'https://registry.npmjs.org'

preferInteractive: true

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.1.1.cjs
