changesetIgnorePatterns:
  - "**/__tests__/**"
  - "**/__mock__/**"
  - "**/*.spec.{ts,tsx}"

enableGlobalCache: false

enableInlineBuilds: true

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  likec4:
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
    npmPublishRegistry: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferInteractive: true

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-3.6.1.cjs
