packages:
  - apps/*
  - styled-system/*
  - packages/*
  - "!packages/create-likec4"

catalog:
  typescript: 5.9.2
  wireit: 0.14.12
  wrangler: 4.22.0
  "@types/node": ~20.19.2
  unbuild: 3.5.0
  turbo: 2.5.5
  tsx: 4.20.3
  zx: 8.5.5
  playwright: 1.54.2

catalogs:
  utils:
    strip-indent: ^4.0.0
    remeda: ^2.23.1
    type-fest: ^4.41.0
    fast-equals: ^5.2.2
    std-env: ^3.9.0
    consola: ^3.4.2
    "@types/chroma-js": ^3.1.1
    chroma-js: ^3.1.2
    "@hpcc-js/wasm-graphviz": 1.10.0
    valibot: ^1.1.0
    "@valibot/to-json-schema": ^1.3.0
    esm-env: ^1.2.2
    json5: ^2.2.3
    object-hash: ^3.0.0
    nano-spawn: ^1.0.2
    picomatch: ^4.0.3
    "@types/picomatch": ^4.0.2
    p-timeout: 6.1.4
    p-debounce: 4.0.0
    p-queue: 8.1.0
    p-limit: 6.2.0
    fdir: 6.4.6
    package-manager-detector: 1.3.0
    ufo: 1.6.1
    zod: 3.25.67
    sharp: 0.34.2
    nanoid: 5.1.5
    "@logtape/logtape": ^0.12.2
    safe-stringify: ^1.2.0
    "@types/natural-compare-lite": "^1.4.2"
    "natural-compare-lite": "^1.4.0"

  esbuild:
    esbuild: 0.25.5
    esbuild-node-externals: 1.18.0
    esbuild-plugins-node-modules-polyfill: 1.7.1
  react:
    react: ^19.1.1
    react-dom: ^19.1.1
    "@types/react": 19.1.9
    "@types/react-dom": 19.1.7
    react-error-boundary: ^6.0.0
    "@tabler/icons-react": 3.34.1
    clsx: ^2.1.1
    nanostores: 1.0.1
    "@nanostores/react": 1.0.0
    motion: ^12.23.11
    "@react-hookz/web": ^25.1.1
  router:
    "@tanstack/react-router": ^1.114.13
    "@tanstack/router-vite-plugin": ^1.114.13
    "@tanstack/router-cli": ^1.114.13
  mantine:
    "@mantine/core": 8.2.2
    "@mantine/hooks": 8.2.2
    "@mantine/vanilla-extract": 8.2.2
    "@mantine/modals": 8.2.2
    "@mantine/notifications": 8.2.2
    "@mantine/colors-generator": 8.2.2
  vite:
    "@vitejs/plugin-react": ^4.6.0
    vite: ^6.3.5
    vite-plugin-dts: ^4.5.4
    vite-plugin-node-polyfills: ^0.23.0
    vite-tsconfig-paths: ^5.1.4
    rollup: ^4.44.0
  vitest:
    vitest: 3.2.4
    "@vitest/ui": 3.2.4
  css:
    postcss: 8.5.5
    "@pandacss/dev": ^0.54.0
    "@pandacss/preset-panda": ^0.54.0
  vscode:
    vscode-jsonrpc: 8.2.1
    vscode-languageclient: 9.0.1
    vscode-languageserver: 9.0.1
    vscode-languageserver-protocol: 3.17.5
    vscode-languageserver-types: 3.17.5
    vscode-uri: 3.1.0
    vscode-oniguruma: 2.0.1
    vscode-textmate: 9.2.0
    "@types/vscode": ^1.84.0
  xyflow:
    "@xyflow/react": 12.6.4
    "@xyflow/system": 0.0.61
  langium:
    langium: 3.5.0
    langium-cli: 3.5.2
  astro:
    "@astrojs/check": ^0.9.4
    "@astrojs/react": 4.3.0
    "@astrojs/starlight": 0.34.4
    "@expressive-code/plugin-collapsible-sections": ^0.41.2
    "@expressive-code/plugin-line-numbers": ^0.41.2
    astro: 5.10.1
    astro-og-canvas: ^0.7.0
    starlight-heading-badges: ^0.5.0
    starlight-image-zoom: ^0.12.0
    starlight-links-validator: ^0.16.0
    starlight-package-managers: ^0.11.0
    shiki: ^3.6.0
  mcp:
    "@modelcontextprotocol/sdk": ^1.13.2
  hono:
    hono: ^4.8.3
    hono-sessions: ^0.7.3
    "@hono/node-server": ^1.14.4
  xstate:
    xstate: ^5.20.1
    "@xstate/react": ^5.0.5

onlyBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd
