packages:
  - "apps/*"
  - "styled-system/*"
  - "packages/*"
  - "!packages/create-likec4"

catalog:
  typescript: "^5.8.3"
  wireit: "^0.14.11"
  wrangler: "4.7.2"
  "@types/node": "^20.17.30"
  unbuild: "^3.5.0"
  turbo: "^2.5.0"
  tsx: "~4.19.3"

catalogs:
  utils:
    remeda: ^2.21.2
    type-fest: "^4.39.1"
    fast-equals: "^5.2.2"
    "@react-hookz/web": "^25.1.0"
    std-env: "^3.9.0"
    consola: "^3.4.2"
    "@hpcc-js/wasm-graphviz": "1.7.0"
    valibot: "^1.0.0"
    "@valibot/to-json-schema": "^1.0.0"
    esm-env: "^1.2.2"
    json5: "^2.2.3"
    object-hash: "^3.0.0"
    picomatch: "^4.0.2"
    "@types/picomatch": "^4.0.0"
  esbuild:
    esbuild: "^0.25.2"
    esbuild-node-externals: "^1.18.0"
    esbuild-plugins-node-modules-polyfill: "^1.7.0"
  react:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4
    react-error-boundary: "^5.0.0"
    "@tabler/icons-react": "3.31.0"
    clsx: "^2.1.1"
    nanostores: "0.11.4"
    "@nanostores/react": "0.8.4"
    framer-motion: "^12.6.3"
  router:
    "@tanstack/react-router": ^1.114.13
    "@tanstack/router-vite-plugin": ^1.114.13
    "@tanstack/router-cli": ^1.114.13
  mantine:
    "@mantine/core": "7.17.4"
    "@mantine/hooks": "7.17.4"
    "@mantine/vanilla-extract": "7.17.4"
    "@mantine/modals": "7.17.4"
    "@mantine/notifications": "7.17.4"
    "@mantine/colors-generator": "7.17.4"
  vite:
    "@vitejs/plugin-react": "^4.3.4"
    vite: "^6.2.5"
    vite-plugin-dts: "^4.5.3"
    vite-plugin-node-polyfills: "^0.23.0"
    vite-tsconfig-paths: "^5.1.4"
    rollup: "^4.39.0"
  vitest:
    vitest: "^3.1.1"
    "@vitest/ui": "^3.1.1"
  css:
    postcss: "^8.5.3"
    "@pandacss/dev": "^0.53.3"
    "@pandacss/preset-panda": "^0.53.3"
  vscode:
    vscode-jsonrpc: "8.2.0"
    vscode-languageclient: "9.0.1"
    vscode-languageserver: "9.0.1"
    vscode-languageserver-protocol: "3.17.5"
    vscode-languageserver-types: "3.17.5"
    vscode-uri: "3.1.0"
    vscode-oniguruma: "2.0.1"
    vscode-textmate: "9.2.0"
    "@types/vscode": "^1.84.0"
  xyflow:
    "@xyflow/react": "^12.5.4"
    "@xyflow/system": "^0.0.54"
  langium:
    langium: "3.4.0"
    langium-cli: "3.4.0"

  astro:
    "@astrojs/check": "^0.9.4"
    "@astrojs/react": "4.2.3"
    "@astrojs/starlight": "0.33.0"
    "@expressive-code/plugin-collapsible-sections": "^0.40.2"
    "@expressive-code/plugin-line-numbers": "^0.40.2"
    astro: "5.6.1"
    astro-og-canvas: "^0.7.0"
    starlight-heading-badges: "^0.5.0"
    starlight-links-validator: "^0.15.0"
    starlight-package-managers: "^0.10.0"
    shiki: "^3.2.1"

onlyBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd
