packages:
  - apps/*
  - devops/
  - styled-system/*
  - packages/*
  - '!packages/create-likec4'

catalog:
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@dagrejs/dagre': 1.1.8
  '@types/node': ~22.19.3
  graphology: ^0.26.0
  graphology-dag: ^0.4.1
  graphology-types: ^0.24.8
  oxlint: 1.35.0
  oxlint-tsgolint: 0.10.0
  playwright: 1.56.1
  tsx: 4.21.0
  turbo: 2.7.2
  typescript: 5.9.3
  unbuild: 3.5.0
  wireit: 0.14.12
  zx: 8.8.5

catalogMode: prefer

catalogs:
  astro:
    '@astrojs/check': ^0.9.6
    '@astrojs/react': 4.4.2
    '@astrojs/starlight': 0.37.1
    '@astrojs/starlight-tailwind': ^4.0.2
    '@expressive-code/plugin-collapsible-sections': ^0.41.6
    '@expressive-code/plugin-line-numbers': ^0.41.6
    astro: 5.16.5
    astro-og-canvas: ^0.7.2
    shiki: ^3.20.0
    starlight-heading-badges: ^0.6.1
    starlight-image-zoom: ^0.13.2
    starlight-links-validator: ^0.19.2
    starlight-package-managers: ^0.11.1
  cloudflare:
    '@cloudflare/vite-plugin': ~1.20.1
    wrangler: ~4.58.0
  css:
    '@pandacss/dev': ^1.7.2
    '@pandacss/preset-panda': ^1.7.2
    '@pandacss/types': ^1.7.2
    '@tailwindcss/vite': ^4.1.17
    postcss: 8.5.6
    tailwindcss: ^4.1.17
  esbuild:
    esbuild: 0.27.2
    esbuild-node-externals: 1.20.1
    esbuild-plugins-node-modules-polyfill: 1.7.1
  hono:
    '@hono/node-server': ^1.19.7
    '@hono/oauth-providers': ^0.8.5
    '@hono/zod-validator': ^0.7.6
    hono: ^4.11.1
    hono-sessions: ^0.8.0
  langium:
    langium: 3.5.0
    langium-cli: 3.5.2
  mantine:
    '@mantine/colors-generator': 8.3.10
    '@mantine/core': 8.3.10
    '@mantine/hooks': 8.3.10
    '@mantine/modals': 8.3.10
    '@mantine/notifications': 8.3.10
    '@mantine/vanilla-extract': 8.3.10
  mcp:
    '@modelcontextprotocol/sdk': ^1.25.1
  react:
    '@floating-ui/dom': ^1.7.4
    '@nanostores/media-query': 0.1.2
    '@nanostores/react': 1.0.0
    '@react-hookz/web': ^25.2.0
    '@tabler/icons-react': 3.36.0
    '@types/react': 19.2.7
    '@types/react-dom': 19.2.3
    clsx: ^2.1.1
    motion: ^12.23.26
    nanostores: 1.1.0
    react: 19.2.3
    react-dom: 19.2.3
    react-error-boundary: ^6.0.0
    react-resizable-panels: ^4.0.11
    react-shadow: ^20.6.0
  tanstack:
    '@tanstack/pacer': ^0.17.1
    '@tanstack/pacer-lite': ^0.2.1
    '@tanstack/react-pacer': ^0.19.1
    '@tanstack/react-query': ^5.85.0
    '@tanstack/react-router': ^1.114.13
    '@tanstack/router-cli': ^1.114.13
    '@tanstack/router-vite-plugin': ^1.114.13
  utils:
    '@hpcc-js/wasm-graphviz': 1.17.0
    '@logtape/logtape': ^1.3.5
    '@lume/kiwi': ^0.4.4
    '@types/chroma-js': ^3.1.2
    '@types/natural-compare-lite': ^1.4.2
    '@types/picomatch': ^4.0.2
    bundle-require: ^5.1.0
    caniuse-lite: ^1.0.30001761
    chokidar: ^5.0.0
    chroma-js: ^3.2.0
    citty: ^0.1.6
    consola: ^3.4.2
    date-fns: ^4.1.0
    defu: ^6.1.4
    esm-env: ^1.2.2
    fast-equals: ^6.0.0
    fdir: 6.4.0
    immer: ^11.1.0
    indent-string: ^5.0.0
    json5: ^2.2.3
    khroma: 2.1.0
    nano-spawn: ^2.0.0
    nanoid: 5.1.6
    natural-compare-lite: ^1.4.0
    object-hash: ^3.0.0
    p-debounce: 5.1.0
    p-limit: 7.2.0
    p-queue: 8.1.1
    p-timeout: 6.1.4
    package-manager-detector: 1.6.0
    package-up: ^5.0.0
    picomatch: ^4.0.3
    remeda: ^2.32.0
    safe-stringify: ^1.2.0
    sharp: 0.34.5
    std-env: ^3.10.0
    strip-indent: ^4.1.1
    type-fest: ^4.41.0
    ufo: 1.6.1
    zod: ^3.25.76
  vite:
    '@vitejs/plugin-react': ^5.1.2
    rollup: ^4.53.5
    vite: ^7.3.0
    vite-plugin-dts: ^4.5.4
    vite-plugin-node-polyfills: ^0.24.0
    vite-tsconfig-paths: ^6.0.3
  vitest:
    '@vitest/ui': 4.0.16
    vitest: 4.0.16
  vscode:
    '@types/vscode': ^1.106.1
    vscode-jsonrpc: 8.2.1
    vscode-languageclient: 9.0.1
    vscode-languageserver: 9.0.1
    vscode-languageserver-protocol: 3.17.5
    vscode-languageserver-types: 3.17.5
    vscode-oniguruma: 2.0.1
    vscode-textmate: 9.3.0
    vscode-uri: 3.1.0
  xstate:
    '@xstate/react': 6.0.0
    '@xstate/store': 3.14.0
    xstate: 5.24.0
  xyflow:
    '@xyflow/react': 12.10.0
    '@xyflow/system': 0.0.74
  zod4:
    zod: ^4.2.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - dprint
  - esbuild
  - sharp
  - workerd
  - oxlint
  - wrangler
