packages:
  - "apps/*"
  - "styled-system/*"
  - "packages/*"
  - "!packages/create-likec4"

catalog:
  typescript: "^5.8.3"
  wireit: "^0.14.12"
  wrangler: "4.13.1"
  "@types/node": "^20.17.30"
  unbuild: "^3.5.0"
  turbo: "^2.5.2"
  tsx: "~4.19.3"

catalogs:
  utils:
    remeda: ^2.21.3
    type-fest: "^4.40.0"
    fast-equals: "^5.2.2"
    "@react-hookz/web": "^25.1.1"
    std-env: "^3.9.0"
    consola: "^3.4.2"
    "@hpcc-js/wasm-graphviz": "1.7.0"
    valibot: "^1.0.0"
    "@valibot/to-json-schema": "^1.0.0"
    esm-env: "^1.2.2"
    json5: "^2.2.3"
    object-hash: "^3.0.0"
    picomatch: "^4.0.2"
    "@types/picomatch": "^4.0.0"
    p-timeout: "^6.1.4"
    p-debounce: "^4.0.0"
    p-queue: "^8.1.0"
    p-limit: "^6.2.0"
    fdir: "^6.4.4"
    package-manager-detector: "^1.2.0"
    ufo: "^1.6.1"
    zod: "^3.24.3"
  esbuild:
    esbuild: "^0.25.3"
    esbuild-node-externals: "^1.18.0"
    esbuild-plugins-node-modules-polyfill: "^1.7.0"
  react:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.3
    react-error-boundary: "^5.0.0"
    "@tabler/icons-react": "3.31.0"
    clsx: "^2.1.1"
    nanostores: "1.0.1"
    "@nanostores/react": "1.0.0"
    motion: "^12.9.0"
  router:
    "@tanstack/react-router": ^1.114.13
    "@tanstack/router-vite-plugin": ^1.114.13
    "@tanstack/router-cli": ^1.114.13
  mantine:
    "@mantine/core": "7.17.5"
    "@mantine/hooks": "7.17.5"
    "@mantine/vanilla-extract": "7.17.5"
    "@mantine/modals": "7.17.5"
    "@mantine/notifications": "7.17.5"
    "@mantine/colors-generator": "7.17.5"
  vite:
    "@vitejs/plugin-react": "^4.4.1"
    vite: "^6.3.3"
    vite-plugin-dts: "^4.5.3"
    vite-plugin-node-polyfills: "^0.23.0"
    vite-tsconfig-paths: "^5.1.4"
    rollup: "^4.40.0"
  vitest:
    vitest: "^3.1.2"
    "@vitest/ui": "^3.1.2"
  css:
    postcss: "^8.5.3"
    "@pandacss/dev": "^0.53.6"
    "@pandacss/preset-panda": "^0.53.6"
  vscode:
    vscode-jsonrpc: "8.2.0"
    vscode-languageclient: "9.0.1"
    vscode-languageserver: "9.0.1"
    vscode-languageserver-protocol: "3.17.5"
    vscode-languageserver-types: "3.17.5"
    vscode-uri: "3.1.0"
    vscode-oniguruma: "2.0.1"
    vscode-textmate: "9.2.0"
    "@types/vscode": "^1.84.0"
  xyflow:
    "@xyflow/react": "^12.6.0"
    "@xyflow/system": "^0.0.57"
  langium:
    langium: "3.5.0"
    langium-cli: "3.5.0"

  astro:
    "@astrojs/check": "^0.9.4"
    "@astrojs/react": "4.2.5"
    "@astrojs/starlight": "0.34.0"
    "@expressive-code/plugin-collapsible-sections": "^0.41.2"
    "@expressive-code/plugin-line-numbers": "^0.41.2"
    astro: "5.7.5"
    astro-og-canvas: "^0.7.0"
    starlight-heading-badges: "^0.5.0"
    starlight-links-validator: "^0.16.0"
    starlight-package-managers: "^0.11.0"
    shiki: "^3.3.0"

  mcp:
    "@modelcontextprotocol/sdk": "^1.10.2"
  hono:
    hono: "^4.7.7"
    hono-sessions: "^0.7.2"
    "@hono/node-server": "^1.14.1"

onlyBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd
