packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: 5.7.3
  wireit: "^0.14.11"
  wrangler: "^3.114.0"
  "@mantine/core": "7.17.1"
  "@mantine/hooks": "7.17.1"
  "@mantine/vanilla-extract": "7.17.1"
  "@mantine/modals": "7.17.1"
  "@mantine/notifications": "7.17.1"
  "@mantine/colors-generator": "7.17.1"
