packages:
  - apps/*
  - devops/
  - styled-system/*
  - packages/*
  - "!packages/create-likec4"

catalog:
  "@dagrejs/dagre": 1.1.5
  "@types/node": ~20.19.22
  graphology: ^0.25.4
  graphology-dag: ^0.4.1
  graphology-types: ^0.24.8
  oxlint: 1.24.0
  oxlint-tsgolint: ^0.2.1
  playwright: 1.56.1
  tsx: 4.20.6
  turbo: 2.5.8
  typescript: 5.9.3
  unbuild: 3.5.0
  vite-plugin-dts: 4.5.4
  vite-tsconfig-paths: ^5.1.4
  wireit: 0.14.12
  zx: 8.8.5

catalogMode: prefer

catalogs:
  astro:
    "@astrojs/check": ^0.9.5
    "@astrojs/react": 4.4.0
    "@astrojs/starlight": 0.36.1
    "@astrojs/starlight-tailwind": ^4.0.1
    "@expressive-code/plugin-collapsible-sections": ^0.41.3
    "@expressive-code/plugin-line-numbers": ^0.41.3
    astro: 5.14.8
    astro-og-canvas: ^0.7.2
    shiki: ^3.13.0
    starlight-heading-badges: ^0.6.1
    starlight-image-zoom: ^0.13.2
    starlight-links-validator: ^0.19.0
    starlight-package-managers: ^0.11.1
    starlight-toc-overview-customizer: ^0.1.0
  cloudflare:
    "@cloudflare/vite-plugin": 1.11.7
    wrangler: ~4.35.0
  css:
    "@pandacss/dev": ^1.4.3
    "@pandacss/preset-panda": ^1.4.3
    "@pandacss/types": ^1.4.3
    "@tailwindcss/vite": ^4.1.14
    postcss: 8.5.6
    tailwindcss: ^4.1.14
  esbuild:
    esbuild: 0.25.11
    esbuild-node-externals: 1.18.0
    esbuild-plugins-node-modules-polyfill: 1.7.1
  hono:
    "@hono/node-server": ^1.19.5
    "@hono/oauth-providers": ^0.8.5
    "@hono/valibot-validator": ^0.5.3
    "@hono/zod-validator": ^0.7.4
    hono: ^4.10.2
    hono-sessions: ^0.8.0
  langium:
    langium: 3.5.0
    langium-cli: 3.5.2
  mantine:
    "@mantine/colors-generator": 8.3.5
    "@mantine/core": 8.3.5
    "@mantine/hooks": 8.3.5
    "@mantine/modals": 8.3.5
    "@mantine/notifications": 8.3.5
    "@mantine/vanilla-extract": 8.3.5
  mcp:
    "@modelcontextprotocol/sdk": ^1.17.5
  react:
    "@floating-ui/dom": ^1.7.4
    "@nanostores/react": 1.0.0
    "@react-hookz/web": ^25.1.1
    "@tabler/icons-react": 3.35.0
    "@types/react": 19.1.16
    "@types/react-dom": 19.1.9
    clsx: ^2.1.1
    motion: ^12.23.24
    nanostores: 1.0.1
    react: 19.1.1
    react-dom: 19.1.1
    react-error-boundary: ^6.0.0
    react-shadow: ^20.6.0
  tanstack:
    "@tanstack/react-query": ^5.85.0
    "@tanstack/react-router": ^1.114.13
    "@tanstack/router-cli": ^1.114.13
    "@tanstack/router-vite-plugin": ^1.114.13
  utils:
    "@hpcc-js/wasm-graphviz": 1.15.0
    "@logtape/logtape": ^0.12.3
    "@lume/kiwi": ^0.4.4
    "@types/chroma-js": ^3.1.1
    "@types/natural-compare-lite": ^1.4.2
    "@types/picomatch": ^4.0.2
    "@valibot/to-json-schema": ^1.3.0
    bundle-require: ^5.1.0
    caniuse-lite: ^1.0.30001751
    chokidar: ^4.0.3
    chroma-js: ^3.1.2
    citty: ^0.1.6
    consola: ^3.4.2
    date-fns: ^4.1.0
    defu: ^6.1.4
    esm-env: ^1.2.2
    fast-equals: ^5.3.2
    fdir: 6.4.0
    indent-string: ^5.0.0
    json5: ^2.2.3
    khroma: 2.1.0
    nano-spawn: ^1.0.3
    nanoid: 5.1.6
    natural-compare-lite: ^1.4.0
    object-hash: ^3.0.0
    p-debounce: 4.0.0
    p-limit: 6.2.0
    p-queue: 8.1.1
    p-timeout: 6.1.4
    package-manager-detector: 1.3.0
    package-up: ^5.0.0
    picomatch: ^4.0.3
    remeda: ^2.32.0
    safe-stringify: ^1.2.0
    sharp: 0.34.3
    std-env: ^3.9.0
    strip-indent: ^4.1.1
    type-fest: ^4.41.0
    ufo: 1.6.1
    valibot: ^1.1.0
    zod: ^3.25.76
  vite:
    "@vitejs/plugin-react": ^5.0.4
    rollup: ^4.52.3
    vite: ^7.1.11
    vite-plugin-dts: ^4.5.4
    vite-plugin-node-polyfills: ^0.24.0
    vite-tsconfig-paths: ^5.1.4
  vitest:
    "@vitest/ui": 3.2.4
    vitest: 3.2.4
  vscode:
    "@types/vscode": ^1.84.0
    vscode-jsonrpc: 8.2.1
    vscode-languageclient: 9.0.1
    vscode-languageserver: 9.0.1
    vscode-languageserver-protocol: 3.17.5
    vscode-languageserver-types: 3.17.5
    vscode-oniguruma: 2.0.1
    vscode-textmate: 9.2.0
    vscode-uri: 3.1.0
  xstate:
    "@xstate/react": ^6.0.0
    xstate: ^5.23.0
  xyflow:
    "@xyflow/react": 12.9.0
    "@xyflow/system": 0.0.71

onlyBuiltDependencies:
  - dprint
  - esbuild
  - sharp
  - workerd
  - oxlint
  - wrangler
