// DO NOT EDIT MANUALLY
// Auto-generated by
//  $ yarn generate:stories

import { LikeC4ViewStory } from './likec4'

export const index = LikeC4ViewStory.bind({})
index.storyName = 'index'
index.args = {
  viewId: 'index'
}

export const customer = LikeC4ViewStory.bind({})
customer.storyName = 'customer'
customer.args = {
  viewId: 'customer'
}

export const cloud = LikeC4ViewStory.bind({})
cloud.storyName = 'cloud'
cloud.args = {
  viewId: 'cloud'
}

export const cloudui = LikeC4ViewStory.bind({})
cloudui.storyName = 'cloud_ui'
cloudui.args = {
  viewId: 'cloud_ui'
}

export const cloudbackend = LikeC4ViewStory.bind({})
cloudbackend.storyName = 'cloud_backend'
cloudbackend.args = {
  viewId: 'cloud_backend'
}

export const cloudgraphql = LikeC4ViewStory.bind({})
cloudgraphql.storyName = 'cloud_graphql'
cloudgraphql.args = {
  viewId: 'cloud_graphql'
}

export const cloudcms = LikeC4ViewStory.bind({})
cloudcms.storyName = 'cloud_cms'
cloudcms.args = {
  viewId: 'cloud_cms'
}

export const amazon = LikeC4ViewStory.bind({})
amazon.storyName = 'amazon'
amazon.args = {
  viewId: 'amazon'
}

export const amazonrds = LikeC4ViewStory.bind({})
amazonrds.storyName = 'amazon_rds'
amazonrds.args = {
  viewId: 'amazon_rds'
}

export const amazoncognito = LikeC4ViewStory.bind({})
amazoncognito.storyName = 'amazon_cognito'
amazoncognito.args = {
  viewId: 'amazon_cognito'
}

export const premium = LikeC4ViewStory.bind({})
premium.storyName = 'premium'
premium.args = {
  viewId: 'premium'
}
