// DO NOT EDIT MANUALLY
// Auto-generated by
//  $ yarn generate:stories

import { LikeC4ViewStory } from './likec4'

export const themecolors = LikeC4ViewStory.bind({})
themecolors.storyName = 'all'
themecolors.args = {
  viewId: 'themecolors'
}

export const themecolorprimary = LikeC4ViewStory.bind({})
themecolorprimary.storyName = 'primary'
themecolorprimary.args = {
  viewId: 'themecolor_primary'
}

export const themecolorsecondary = LikeC4ViewStory.bind({})
themecolorsecondary.storyName = 'secondary'
themecolorsecondary.args = {
  viewId: 'themecolor_secondary'
}

export const themecolormuted = LikeC4ViewStory.bind({})
themecolormuted.storyName = 'muted'
themecolormuted.args = {
  viewId: 'themecolor_muted'
}

export const themecolorblue = LikeC4ViewStory.bind({})
themecolorblue.storyName = 'blue'
themecolorblue.args = {
  viewId: 'themecolor_blue'
}

export const themecolorsky = LikeC4ViewStory.bind({})
themecolorsky.storyName = 'sky'
themecolorsky.args = {
  viewId: 'themecolor_sky'
}

export const themecolorslate = LikeC4ViewStory.bind({})
themecolorslate.storyName = 'slate'
themecolorslate.args = {
  viewId: 'themecolor_slate'
}

export const themecolorgray = LikeC4ViewStory.bind({})
themecolorgray.storyName = 'gray'
themecolorgray.args = {
  viewId: 'themecolor_gray'
}

export const themecolorred = LikeC4ViewStory.bind({})
themecolorred.storyName = 'red'
themecolorred.args = {
  viewId: 'themecolor_red'
}

export const themecolorgreen = LikeC4ViewStory.bind({})
themecolorgreen.storyName = 'green'
themecolorgreen.args = {
  viewId: 'themecolor_green'
}

export const themecoloramber = LikeC4ViewStory.bind({})
themecoloramber.storyName = 'amber'
themecoloramber.args = {
  viewId: 'themecolor_amber'
}

export const themecolorindigo = LikeC4ViewStory.bind({})
themecolorindigo.storyName = 'indigo'
themecolorindigo.args = {
  viewId: 'themecolor_indigo'
}
