// This file is auto-generated by scripts/generate.ts

export const staticCssIncludeProps = {
  fill: [
    'likec4.element.fill',
  ],
  stroke: [
    'likec4.element.stroke',
    'likec4.relation.line',
  ],
  color: [
    'likec4.element.hiContrast',
    'likec4.element.loContrast',
    'likec4.compound.title',
    'likec4.relation.label',
    'mantine.colors.text',
    'mantine.colors.dimmed',
    'mantine.colors.defaultColor',
    'mantine.colors.default',
    'mantine.colors.placeholder',
  ],
  background: [
    'likec4.background',
    'mantine.colors.body',
    'mantine.colors.defaultHover',
    'likec4.relation.label.bg',
  ],
}

export const conditions = {
  likec4ColorAmber: ':where([data-likec4-color=\'amber\']) &',
  likec4ColorBlue: ':where([data-likec4-color=\'blue\']) &',
  likec4ColorGray: ':where([data-likec4-color=\'gray\']) &',
  likec4ColorSlate: ':where([data-likec4-color=\'slate\']) &',
  likec4ColorGreen: ':where([data-likec4-color=\'green\']) &',
  likec4ColorIndigo: ':where([data-likec4-color=\'indigo\']) &',
  likec4ColorMuted: ':where([data-likec4-color=\'muted\']) &',
  likec4ColorPrimary: ':where([data-likec4-color=\'primary\']) &',
  likec4ColorRed: ':where([data-likec4-color=\'red\']) &',
  likec4ColorSecondary: ':where([data-likec4-color=\'secondary\']) &',
  likec4ColorSky: ':where([data-likec4-color=\'sky\']) &',
  shapeSizeXs: ':where([data-likec4-shape-size=\'xs\']) &',
  shapeSizeSm: ':where([data-likec4-shape-size=\'sm\']) &',
  shapeSizeMd: ':where([data-likec4-shape-size=\'md\']) &',
  shapeSizeLg: ':where([data-likec4-shape-size=\'lg\']) &',
  shapeSizeXl: ':where([data-likec4-shape-size=\'xl\']) &',
  shapeRectangle: ':where([data-likec4-shape=\'rectangle\']) &',
  shapePerson: ':where([data-likec4-shape=\'person\']) &',
  shapeBrowser: ':where([data-likec4-shape=\'browser\']) &',
  shapeMobile: ':where([data-likec4-shape=\'mobile\']) &',
  shapeCylinder: ':where([data-likec4-shape=\'cylinder\']) &',
  shapeStorage: ':where([data-likec4-shape=\'storage\']) &',
  shapeQueue: ':where([data-likec4-shape=\'queue\']) &',
}

export const globalCss = {
  ':where([data-likec4-text-size=\'xs\'])': {
    '--likec4-text-size': '{fontSizes.likec4.xs}',
  },
  ':where([data-likec4-text-size=\'sm\'])': {
    '--likec4-text-size': '{fontSizes.likec4.sm}',
  },
  ':where([data-likec4-text-size=\'md\'])': {
    '--likec4-text-size': '{fontSizes.likec4.md}',
  },
  ':where([data-likec4-text-size=\'lg\'])': {
    '--likec4-text-size': '{fontSizes.likec4.lg}',
  },
  ':where([data-likec4-text-size=\'xl\'])': {
    '--likec4-text-size': '{fontSizes.likec4.xl}',
  },
  ':where([data-likec4-spacing=\'xs\'])': {
    '--likec4-spacing': '{spacing.likec4.xs}',
  },
  ':where([data-likec4-spacing=\'sm\'])': {
    '--likec4-spacing': '{spacing.likec4.sm}',
  },
  ':where([data-likec4-spacing=\'md\'])': {
    '--likec4-spacing': '{spacing.likec4.md}',
  },
  ':where([data-likec4-spacing=\'lg\'])': {
    '--likec4-spacing': '{spacing.likec4.lg}',
  },
  ':where([data-likec4-spacing=\'xl\'])': {
    '--likec4-spacing': '{spacing.likec4.xl}',
  },
  ':where([data-likec4-color=\'primary\'])': {
    '--colors-likec4-element-fill': '#3b82f6',
    '--colors-likec4-element-stroke': '#2563eb',
  },
  ':where([data-likec4-color=\'primary\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#145ed7',
    '--colors-likec4-element-stroke': '#194bb8',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'primary\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#1a5bc5',
    '--colors-likec4-element-stroke': '#1e49a9',
  },
  ':where([data-likec4-color=\'primary\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#195cc8',
    '--colors-likec4-element-stroke': '#1d4aac',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'primary\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#1e56b1',
    '--colors-likec4-element-stroke': '#204698',
  },
  ':where([data-likec4-color=\'primary\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#1e59ba',
    '--colors-likec4-element-stroke': '#2149a0',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'primary\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#21519f',
    '--colors-likec4-element-stroke': '#224289',
  },
  ':where([data-likec4-color=\'primary\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#2357ad',
    '--colors-likec4-element-stroke': '#244795',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'primary\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#234c8e',
    '--colors-likec4-element-stroke': '#243f7a',
  },
  ':where([data-likec4-color=\'primary\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#2755a0',
    '--colors-likec4-element-stroke': '#27468a',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'primary\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#25467d',
    '--colors-likec4-element-stroke': '#243b6c',
  },
  ':where([data-likec4-color=\'blue\'])': {
    '--colors-likec4-element-fill': '#3b82f6',
    '--colors-likec4-element-stroke': '#2563eb',
  },
  ':where([data-likec4-color=\'blue\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#145ed7',
    '--colors-likec4-element-stroke': '#194bb8',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'blue\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#1a5bc5',
    '--colors-likec4-element-stroke': '#1e49a9',
  },
  ':where([data-likec4-color=\'blue\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#195cc8',
    '--colors-likec4-element-stroke': '#1d4aac',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'blue\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#1e56b1',
    '--colors-likec4-element-stroke': '#204698',
  },
  ':where([data-likec4-color=\'blue\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#1e59ba',
    '--colors-likec4-element-stroke': '#2149a0',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'blue\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#21519f',
    '--colors-likec4-element-stroke': '#224289',
  },
  ':where([data-likec4-color=\'blue\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#2357ad',
    '--colors-likec4-element-stroke': '#244795',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'blue\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#234c8e',
    '--colors-likec4-element-stroke': '#243f7a',
  },
  ':where([data-likec4-color=\'blue\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#2755a0',
    '--colors-likec4-element-stroke': '#27468a',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'blue\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#25467d',
    '--colors-likec4-element-stroke': '#243b6c',
  },
  ':where([data-likec4-color=\'secondary\'])': {
    '--colors-likec4-element-fill': '#0284c7',
    '--colors-likec4-element-stroke': '#0369a1',
  },
  ':where([data-likec4-color=\'secondary\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#086392',
    '--colors-likec4-element-stroke': '#084f76',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'secondary\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#0d5d86',
    '--colors-likec4-element-stroke': '#0b4a6c',
  },
  ':where([data-likec4-color=\'secondary\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#0c5e88',
    '--colors-likec4-element-stroke': '#0b4b6e',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'secondary\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#105579',
    '--colors-likec4-element-stroke': '#0e4462',
  },
  ':where([data-likec4-color=\'secondary\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#10597f',
    '--colors-likec4-element-stroke': '#0e4767',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'secondary\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#134e6c',
    '--colors-likec4-element-stroke': '#103e57',
  },
  ':where([data-likec4-color=\'secondary\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#135475',
    '--colors-likec4-element-stroke': '#11435f',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'secondary\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#154660',
    '--colors-likec4-element-stroke': '#11384e',
  },
  ':where([data-likec4-color=\'secondary\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#164f6c',
    '--colors-likec4-element-stroke': '#133f58',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'secondary\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#163f55',
    '--colors-likec4-element-stroke': '#123345',
  },
  ':where([data-likec4-color=\'sky\'])': {
    '--colors-likec4-element-fill': '#0284c7',
    '--colors-likec4-element-stroke': '#0369a1',
  },
  ':where([data-likec4-color=\'sky\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#086392',
    '--colors-likec4-element-stroke': '#084f76',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'sky\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#0d5d86',
    '--colors-likec4-element-stroke': '#0b4a6c',
  },
  ':where([data-likec4-color=\'sky\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#0c5e88',
    '--colors-likec4-element-stroke': '#0b4b6e',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'sky\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#105579',
    '--colors-likec4-element-stroke': '#0e4462',
  },
  ':where([data-likec4-color=\'sky\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#10597f',
    '--colors-likec4-element-stroke': '#0e4767',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'sky\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#134e6c',
    '--colors-likec4-element-stroke': '#103e57',
  },
  ':where([data-likec4-color=\'sky\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#135475',
    '--colors-likec4-element-stroke': '#11435f',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'sky\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#154660',
    '--colors-likec4-element-stroke': '#11384e',
  },
  ':where([data-likec4-color=\'sky\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#164f6c',
    '--colors-likec4-element-stroke': '#133f58',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'sky\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#163f55',
    '--colors-likec4-element-stroke': '#123345',
  },
  ':where([data-likec4-color=\'muted\'])': {
    '--colors-likec4-element-fill': '#64748b',
    '--colors-likec4-element-stroke': '#475569',
  },
  ':where([data-likec4-color=\'muted\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#4e5a6a',
    '--colors-likec4-element-stroke': '#384250',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'muted\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#4b5563',
    '--colors-likec4-element-stroke': '#363e4b',
  },
  ':where([data-likec4-color=\'muted\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#4c5665',
    '--colors-likec4-element-stroke': '#363f4c',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'muted\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#474f5c',
    '--colors-likec4-element-stroke': '#333a45',
  },
  ':where([data-likec4-color=\'muted\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#4a5360',
    '--colors-likec4-element-stroke': '#353d48',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'muted\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#424a54',
    '--colors-likec4-element-stroke': '#30363f',
  },
  ':where([data-likec4-color=\'muted\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#48505b',
    '--colors-likec4-element-stroke': '#333a44',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'muted\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#3e444d',
    '--colors-likec4-element-stroke': '#2d323a',
  },
  ':where([data-likec4-color=\'muted\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#454c56',
    '--colors-likec4-element-stroke': '#323841',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'muted\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#393e46',
    '--colors-likec4-element-stroke': '#292e34',
  },
  ':where([data-likec4-color=\'slate\'])': {
    '--colors-likec4-element-fill': '#64748b',
    '--colors-likec4-element-stroke': '#475569',
  },
  ':where([data-likec4-color=\'slate\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#4e5a6a',
    '--colors-likec4-element-stroke': '#384250',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'slate\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#4b5563',
    '--colors-likec4-element-stroke': '#363e4b',
  },
  ':where([data-likec4-color=\'slate\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#4c5665',
    '--colors-likec4-element-stroke': '#363f4c',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'slate\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#474f5c',
    '--colors-likec4-element-stroke': '#333a45',
  },
  ':where([data-likec4-color=\'slate\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#4a5360',
    '--colors-likec4-element-stroke': '#353d48',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'slate\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#424a54',
    '--colors-likec4-element-stroke': '#30363f',
  },
  ':where([data-likec4-color=\'slate\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#48505b',
    '--colors-likec4-element-stroke': '#333a44',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'slate\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#3e444d',
    '--colors-likec4-element-stroke': '#2d323a',
  },
  ':where([data-likec4-color=\'slate\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#454c56',
    '--colors-likec4-element-stroke': '#323841',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'slate\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#393e46',
    '--colors-likec4-element-stroke': '#292e34',
  },
  ':where([data-likec4-color=\'gray\'])': {
    '--colors-likec4-element-fill': '#737373',
    '--colors-likec4-element-stroke': '#525252',
  },
  ':where([data-likec4-color=\'gray\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#595959',
    '--colors-likec4-element-stroke': '#3f3f3f',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'gray\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#545454',
    '--colors-likec4-element-stroke': '#3c3c3c',
  },
  ':where([data-likec4-color=\'gray\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#555555',
    '--colors-likec4-element-stroke': '#3d3d3d',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'gray\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#4e4e4e',
    '--colors-likec4-element-stroke': '#383838',
  },
  ':where([data-likec4-color=\'gray\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#525252',
    '--colors-likec4-element-stroke': '#3a3a3a',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'gray\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#484848',
    '--colors-likec4-element-stroke': '#343434',
  },
  ':where([data-likec4-color=\'gray\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#4e4e4e',
    '--colors-likec4-element-stroke': '#383838',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'gray\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#434343',
    '--colors-likec4-element-stroke': '#303030',
  },
  ':where([data-likec4-color=\'gray\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#4b4b4b',
    '--colors-likec4-element-stroke': '#353535',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'gray\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#3d3d3d',
    '--colors-likec4-element-stroke': '#2b2b2b',
  },
  ':where([data-likec4-color=\'red\'])': {
    '--colors-likec4-element-fill': '#AC4D39',
    '--colors-likec4-element-stroke': '#853A2D',
  },
  ':where([data-likec4-color=\'red\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#803e30',
    '--colors-likec4-element-stroke': '#632f26',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'red\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#773d30',
    '--colors-likec4-element-stroke': '#5c2e26',
  },
  ':where([data-likec4-color=\'red\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#793d31',
    '--colors-likec4-element-stroke': '#5e2e26',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'red\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#6c3a2f',
    '--colors-likec4-element-stroke': '#542c25',
  },
  ':where([data-likec4-color=\'red\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#723c31',
    '--colors-likec4-element-stroke': '#582e27',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'red\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#62372e',
    '--colors-likec4-element-stroke': '#4c2a24',
  },
  ':where([data-likec4-color=\'red\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#6a3b31',
    '--colors-likec4-element-stroke': '#522d27',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'red\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#58342c',
    '--colors-likec4-element-stroke': '#442823',
  },
  ':where([data-likec4-color=\'red\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#633a31',
    '--colors-likec4-element-stroke': '#4d2c27',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'red\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#4f312a',
    '--colors-likec4-element-stroke': '#3d2521',
  },
  ':where([data-likec4-color=\'green\'])': {
    '--colors-likec4-element-fill': '#428a4f',
    '--colors-likec4-element-stroke': '#2d5d39',
  },
  ':where([data-likec4-color=\'green\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#35683e',
    '--colors-likec4-element-stroke': '#24462d',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'green\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#34613c',
    '--colors-likec4-element-stroke': '#24412b',
  },
  ':where([data-likec4-color=\'green\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#35623d',
    '--colors-likec4-element-stroke': '#24422c',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'green\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#325839',
    '--colors-likec4-element-stroke': '#223c29',
  },
  ':where([data-likec4-color=\'green\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#345d3c',
    '--colors-likec4-element-stroke': '#243e2a',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'green\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#305136',
    '--colors-likec4-element-stroke': '#213626',
  },
  ':where([data-likec4-color=\'green\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#33573a',
    '--colors-likec4-element-stroke': '#233b29',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'green\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#2d4932',
    '--colors-likec4-element-stroke': '#1f3123',
  },
  ':where([data-likec4-color=\'green\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#335238',
    '--colors-likec4-element-stroke': '#223728',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'green\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#2b422f',
    '--colors-likec4-element-stroke': '#1d2c21',
  },
  ':where([data-likec4-color=\'amber\'])': {
    '--colors-likec4-element-fill': '#A35829',
    '--colors-likec4-element-stroke': '#7E451D',
  },
  ':where([data-likec4-color=\'amber\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#794524',
    '--colors-likec4-element-stroke': '#5e361a',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'amber\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#704225',
    '--colors-likec4-element-stroke': '#56331b',
  },
  ':where([data-likec4-color=\'amber\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#724325',
    '--colors-likec4-element-stroke': '#58341b',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'amber\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#663e25',
    '--colors-likec4-element-stroke': '#4e301b',
  },
  ':where([data-likec4-color=\'amber\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#6b4126',
    '--colors-likec4-element-stroke': '#52321c',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'amber\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#5c3a25',
    '--colors-likec4-element-stroke': '#472d1b',
  },
  ':where([data-likec4-color=\'amber\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#643e27',
    '--colors-likec4-element-stroke': '#4d301d',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'amber\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#533624',
    '--colors-likec4-element-stroke': '#402a1a',
  },
  ':where([data-likec4-color=\'amber\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#5d3c28',
    '--colors-likec4-element-stroke': '#472f1d',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'amber\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#493223',
    '--colors-likec4-element-stroke': '#38261a',
  },
  ':where([data-likec4-color=\'indigo\'])': {
    '--colors-likec4-element-fill': '#6366f1',
    '--colors-likec4-element-stroke': '#4f46e5',
  },
  ':where([data-likec4-color=\'indigo\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#2529e1',
    '--colors-likec4-element-stroke': '#2d24c2',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'indigo\'][data-compound-depth=\'1\'])': {
    '--colors-likec4-element-fill': '#2529d3',
    '--colors-likec4-element-stroke': '#3028b2',
  },
  ':where([data-likec4-color=\'indigo\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#2428d7',
    '--colors-likec4-element-stroke': '#3028b5',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'indigo\'][data-compound-depth=\'2\'])': {
    '--colors-likec4-element-fill': '#282bbf',
    '--colors-likec4-element-stroke': '#312aa1',
  },
  ':where([data-likec4-color=\'indigo\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#292cc8',
    '--colors-likec4-element-stroke': '#322ba9',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'indigo\'][data-compound-depth=\'3\'])': {
    '--colors-likec4-element-fill': '#2b2dac',
    '--colors-likec4-element-stroke': '#312b91',
  },
  ':where([data-likec4-color=\'indigo\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#2d30ba',
    '--colors-likec4-element-stroke': '#342e9e',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'indigo\'][data-compound-depth=\'4\'])': {
    '--colors-likec4-element-fill': '#2c2f99',
    '--colors-likec4-element-stroke': '#302c82',
  },
  ':where([data-likec4-color=\'indigo\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#3133ac',
    '--colors-likec4-element-stroke': '#363092',
  },
  ':where([data-mantine-color-scheme="dark"]) :where([data-likec4-color=\'indigo\'][data-compound-depth=\'5\'])': {
    '--colors-likec4-element-fill': '#2d2f87',
    '--colors-likec4-element-stroke': '#2f2b73',
  },
}

export const theme = {
  keyframes: {
    spin: {
      to: {
        transform: 'rotate(360deg)',
      },
    },
    ping: {
      '75%, 100%': {
        transform: 'scale(2)',
        opacity: '0',
      },
    },
    pulse: {
      '50%': {
        opacity: '.5',
      },
    },
    bounce: {
      '0%, 100%': {
        transform: 'translateY(-25%)',
        animationTimingFunction: 'cubic-bezier(0.8,0,1,1)',
      },
      '50%': {
        transform: 'none',
        animationTimingFunction: 'cubic-bezier(0,0,0.2,1)',
      },
    },
  },
  breakpoints: {
    xs: '36em',
    sm: '48em',
    md: '62em',
    lg: '75em',
    xl: '88em',
  },
  tokens: {
    aspectRatios: {
      square: {
        value: '1 / 1',
      },
      landscape: {
        value: '4 / 3',
      },
      portrait: {
        value: '3 / 4',
      },
      wide: {
        value: '16 / 9',
      },
      ultrawide: {
        value: '18 / 5',
      },
      golden: {
        value: '1.618 / 1',
      },
    },
    borders: {
      none: {
        value: 'none',
      },
    },
    easings: {
      default: {
        value: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      linear: {
        value: 'linear',
      },
      in: {
        value: 'cubic-bezier(0.4, 0, 1, 1)',
      },
      out: {
        value: 'cubic-bezier(0, 0, 0.40, 1)',
      },
      'in-out': {
        value: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      inOut: {
        value: 'cubic-bezier(0.50, 0, 0.2, 1)',
      },
    },
    durations: {
      fastest: {
        value: '50ms',
      },
      faster: {
        value: '100ms',
      },
      fast: {
        value: '150ms',
      },
      normal: {
        value: '200ms',
      },
      slow: {
        value: '300ms',
      },
      slower: {
        value: '400ms',
      },
      slowest: {
        value: '500ms',
      },
    },
    radii: {
      xs: {
        value: 'var(--mantine-radius-xs)',
      },
      sm: {
        value: 'var(--mantine-radius-sm)',
      },
      md: {
        value: 'var(--mantine-radius-md)',
      },
      lg: {
        value: 'var(--mantine-radius-lg)',
      },
      xl: {
        value: 'var(--mantine-radius-xl)',
      },
    },
    fontWeights: {
      thin: {
        value: '100',
      },
      extralight: {
        value: '200',
      },
      light: {
        value: '300',
      },
      normal: {
        value: '400',
      },
      medium: {
        value: '500',
      },
      semibold: {
        value: '600',
      },
      bold: {
        value: '700',
      },
      extrabold: {
        value: '800',
      },
      black: {
        value: '900',
      },
    },
    lineHeights: {
      xs: {
        value: '1.4',
      },
      sm: {
        value: '1.45',
      },
      md: {
        value: '1.55',
      },
      lg: {
        value: '1.6',
      },
      xl: {
        value: '1.65',
      },
    },
    fonts: {
      sans: {
        value: [
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      serif: {
        value: [
          'ui-serif',
          'Georgia',
          'Cambria',
          '"Times New Roman"',
          'Times',
          'serif',
        ],
      },
      mono: {
        value: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      body: {
        value: 'var(--likec4-app-font, var(--likec4-app-font-default))',
      },
      likec4: {
        DEFAULT: {
          value: 'var(--likec4-app-font, var(--likec4-app-font-default))',
        },
        element: {
          value: 'var(--likec4-element-font, {fonts.likec4})',
        },
        compound: {
          value: 'var(--likec4-compound-font, {fonts.likec4})',
        },
        relation: {
          value: 'var(--likec4-relation-font, {fonts.likec4})',
        },
      },
    },
    letterSpacings: {
      tighter: {
        value: '-0.05em',
      },
      tight: {
        value: '-0.025em',
      },
      normal: {
        value: '0em',
      },
      wide: {
        value: '0.025em',
      },
      wider: {
        value: '0.05em',
      },
      widest: {
        value: '0.1em',
      },
    },
    fontSizes: {
      xs: {
        value: 'calc(0.75rem * var(--mantine-scale))',
      },
      sm: {
        value: 'calc(0.875rem * var(--mantine-scale))',
      },
      md: {
        value: 'calc(1rem * var(--mantine-scale))',
      },
      lg: {
        value: 'calc(1.125rem * var(--mantine-scale))',
      },
      xl: {
        value: 'calc(1.25rem * var(--mantine-scale))',
      },
      '2xs': {
        value: 'calc(0.625rem * var(--mantine-scale))',
      },
      likec4: {
        xs: {
          description: 'LikeC4 style text size: xs',
          value: 'calc(0.75rem * var(--mantine-scale))',
        },
        sm: {
          description: 'LikeC4 style text size: sm',
          value: 'calc(0.875rem * var(--mantine-scale))',
        },
        md: {
          description: 'LikeC4 style text size: md',
          value: 'calc(1.1875rem * var(--mantine-scale))',
        },
        lg: {
          description: 'LikeC4 style text size: lg',
          value: 'calc(1.5rem * var(--mantine-scale))',
        },
        xl: {
          description: 'LikeC4 style text size: xl',
          value: 'calc(2rem * var(--mantine-scale))',
        },
      },
    },
    shadows: {
      xs: {
        value:
          '0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), 0 calc(0.0625rem * var(--mantine-scale)) calc(0.125rem * var(--mantine-scale)) rgba(0, 0, 0, 0.1)',
      },
      sm: {
        value:
          '0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(0.625rem * var(--mantine-scale)) calc(0.9375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.4375rem * var(--mantine-scale)) calc(0.4375rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale))',
      },
      md: {
        value:
          '0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(1.25rem * var(--mantine-scale)) calc(1.5625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.625rem * var(--mantine-scale)) calc(0.625rem * var(--mantine-scale)) calc(-0.3125rem * var(--mantine-scale))',
      },
      lg: {
        value:
          '0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(1.75rem * var(--mantine-scale)) calc(1.4375rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(0.75rem * var(--mantine-scale)) calc(0.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale))',
      },
      xl: {
        value:
          '0 calc(0.0625rem * var(--mantine-scale)) calc(0.1875rem * var(--mantine-scale)) rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05) 0 calc(2.25rem * var(--mantine-scale)) calc(1.75rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale)), rgba(0, 0, 0, 0.04) 0 calc(1.0625rem * var(--mantine-scale)) calc(1.0625rem * var(--mantine-scale)) calc(-0.4375rem * var(--mantine-scale))',
      },
    },
    blurs: {
      sm: {
        value: '4px',
      },
      base: {
        value: '8px',
      },
      md: {
        value: '12px',
      },
      lg: {
        value: '16px',
      },
      xl: {
        value: '24px',
      },
      '2xl': {
        value: '40px',
      },
      '3xl': {
        value: '64px',
      },
    },
    spacing: {
      '0': {
        value: '0px',
      },
      '2': {
        value: '2px',
      },
      '4': {
        value: '4px',
      },
      '8': {
        value: '8px',
      },
      xs: {
        value: 'calc(0.625rem * var(--mantine-scale))',
      },
      sm: {
        value: 'calc(0.75rem * var(--mantine-scale))',
      },
      md: {
        value: 'calc(1rem * var(--mantine-scale))',
      },
      lg: {
        value: 'calc(1.25rem * var(--mantine-scale))',
      },
      xl: {
        value: 'calc(2rem * var(--mantine-scale))',
      },
      micro: {
        value: '4px',
      },
      '2xs': {
        value: '8px',
      },
      likec4: {
        xs: {
          description: 'LikeC4 style spacing: xs',
          value: '8px',
        },
        sm: {
          description: 'LikeC4 style spacing: sm',
          value: '10px',
        },
        md: {
          description: 'LikeC4 style spacing: md',
          value: '16px',
        },
        lg: {
          description: 'LikeC4 style spacing: lg',
          value: '24px',
        },
        xl: {
          description: 'LikeC4 style spacing: xl',
          value: '32px',
        },
      },
    },
    sizes: {},
    animations: {
      spin: {
        value: 'spin 1s linear infinite',
      },
      ping: {
        value: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      pulse: {
        value: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      bounce: {
        value: 'bounce 1s infinite',
      },
    },
    containerNames: {},
    colors: {
      mantine: {
        colors: {
          'primary[0]': {
            value: 'var(--mantine-primary-color-0)',
          },
          'primary[1]': {
            value: 'var(--mantine-primary-color-1)',
          },
          'primary[2]': {
            value: 'var(--mantine-primary-color-2)',
          },
          'primary[3]': {
            value: 'var(--mantine-primary-color-3)',
          },
          'primary[4]': {
            value: 'var(--mantine-primary-color-4)',
          },
          'primary[5]': {
            value: 'var(--mantine-primary-color-5)',
          },
          'primary[6]': {
            value: 'var(--mantine-primary-color-6)',
          },
          'primary[7]': {
            value: 'var(--mantine-primary-color-7)',
          },
          'primary[8]': {
            value: 'var(--mantine-primary-color-8)',
          },
          'primary[9]': {
            value: 'var(--mantine-primary-color-9)',
          },
          'primary.filled': {
            value: 'var(--mantine-primary-color-filled)',
          },
          'primary.filledHover': {
            value: 'var(--mantine-primary-color-filled-hover)',
          },
          'primary.light': {
            value: 'var(--mantine-primary-color-light)',
          },
          'primary.lightHover': {
            value: 'var(--mantine-primary-color-light-hover)',
          },
          'primary.lightColor': {
            value: 'var(--mantine-primary-color-light-color)',
          },
          'primary.outline': {
            value: 'var(--mantine-primary-color-outline)',
          },
          'primary.outlineHover': {
            value: 'var(--mantine-primary-color-outline-hover)',
          },
          primary: {
            value: 'var(--mantine-primary-color-filled)',
          },
          white: {
            value: 'var(--mantine-color-white)',
          },
          text: {
            value: 'var(--mantine-color-text)',
          },
          body: {
            value: 'var(--mantine-color-body)',
          },
          dimmed: {
            value: 'var(--mantine-color-dimmed)',
          },
          defaultBorder: {
            value: 'var(--mantine-color-default-border)',
          },
          defaultColor: {
            value: 'var(--mantine-color-default-color)',
          },
          defaultHover: {
            value: 'var(--mantine-color-default-hover)',
          },
          default: {
            value: 'var(--mantine-color-default)',
          },
          error: {
            value: 'var(--mantine-color-error)',
          },
          placeholder: {
            value: 'var(--mantine-color-placeholder)',
          },
          'gray[0]': {
            value: 'var(--mantine-color-gray-0)',
          },
          'gray[1]': {
            value: 'var(--mantine-color-gray-1)',
          },
          'gray[2]': {
            value: 'var(--mantine-color-gray-2)',
          },
          'gray[3]': {
            value: 'var(--mantine-color-gray-3)',
          },
          'gray[4]': {
            value: 'var(--mantine-color-gray-4)',
          },
          'gray[5]': {
            value: 'var(--mantine-color-gray-5)',
          },
          'gray[6]': {
            value: 'var(--mantine-color-gray-6)',
          },
          'gray[7]': {
            value: 'var(--mantine-color-gray-7)',
          },
          'gray[8]': {
            value: 'var(--mantine-color-gray-8)',
          },
          'gray[9]': {
            value: 'var(--mantine-color-gray-9)',
          },
          'gray.filled': {
            value: 'var(--mantine-color-gray-filled)',
          },
          'gray.filledHover': {
            value: 'var(--mantine-color-gray-filled-hover)',
          },
          'gray.light': {
            value: 'var(--mantine-color-gray-light)',
          },
          'gray.lightHover': {
            value: 'var(--mantine-color-gray-light-hover)',
          },
          'gray.lightColor': {
            value: 'var(--mantine-color-gray-light-color)',
          },
          'gray.outline': {
            value: 'var(--mantine-color-gray-outline)',
          },
          'gray.outlineHover': {
            value: 'var(--mantine-color-gray-outline-hover)',
          },
          gray: {
            value: 'var(--mantine-color-gray-6)',
          },
          'dark[0]': {
            value: 'var(--mantine-color-dark-0)',
          },
          'dark[1]': {
            value: 'var(--mantine-color-dark-1)',
          },
          'dark[2]': {
            value: 'var(--mantine-color-dark-2)',
          },
          'dark[3]': {
            value: 'var(--mantine-color-dark-3)',
          },
          'dark[4]': {
            value: 'var(--mantine-color-dark-4)',
          },
          'dark[5]': {
            value: 'var(--mantine-color-dark-5)',
          },
          'dark[6]': {
            value: 'var(--mantine-color-dark-6)',
          },
          'dark[7]': {
            value: 'var(--mantine-color-dark-7)',
          },
          'dark[8]': {
            value: 'var(--mantine-color-dark-8)',
          },
          'dark[9]': {
            value: 'var(--mantine-color-dark-9)',
          },
          'dark.filled': {
            value: 'var(--mantine-color-dark-filled)',
          },
          'dark.filledHover': {
            value: 'var(--mantine-color-dark-filled-hover)',
          },
          'dark.light': {
            value: 'var(--mantine-color-dark-light)',
          },
          'dark.lightHover': {
            value: 'var(--mantine-color-dark-light-hover)',
          },
          'dark.lightColor': {
            value: 'var(--mantine-color-dark-light-color)',
          },
          'dark.outline': {
            value: 'var(--mantine-color-dark-outline)',
          },
          'dark.outlineHover': {
            value: 'var(--mantine-color-dark-outline-hover)',
          },
          dark: {
            value: 'var(--mantine-color-dark-6)',
          },
          'orange[0]': {
            value: 'var(--mantine-color-orange-0)',
          },
          'orange[1]': {
            value: 'var(--mantine-color-orange-1)',
          },
          'orange[2]': {
            value: 'var(--mantine-color-orange-2)',
          },
          'orange[3]': {
            value: 'var(--mantine-color-orange-3)',
          },
          'orange[4]': {
            value: 'var(--mantine-color-orange-4)',
          },
          'orange[5]': {
            value: 'var(--mantine-color-orange-5)',
          },
          'orange[6]': {
            value: 'var(--mantine-color-orange-6)',
          },
          'orange[7]': {
            value: 'var(--mantine-color-orange-7)',
          },
          'orange[8]': {
            value: 'var(--mantine-color-orange-8)',
          },
          'orange[9]': {
            value: 'var(--mantine-color-orange-9)',
          },
          'orange.filled': {
            value: 'var(--mantine-color-orange-filled)',
          },
          'orange.filledHover': {
            value: 'var(--mantine-color-orange-filled-hover)',
          },
          'orange.light': {
            value: 'var(--mantine-color-orange-light)',
          },
          'orange.lightHover': {
            value: 'var(--mantine-color-orange-light-hover)',
          },
          'orange.lightColor': {
            value: 'var(--mantine-color-orange-light-color)',
          },
          'orange.outline': {
            value: 'var(--mantine-color-orange-outline)',
          },
          'orange.outlineHover': {
            value: 'var(--mantine-color-orange-outline-hover)',
          },
          orange: {
            value: 'var(--mantine-color-orange-6)',
          },
          'teal[0]': {
            value: 'var(--mantine-color-teal-0)',
          },
          'teal[1]': {
            value: 'var(--mantine-color-teal-1)',
          },
          'teal[2]': {
            value: 'var(--mantine-color-teal-2)',
          },
          'teal[3]': {
            value: 'var(--mantine-color-teal-3)',
          },
          'teal[4]': {
            value: 'var(--mantine-color-teal-4)',
          },
          'teal[5]': {
            value: 'var(--mantine-color-teal-5)',
          },
          'teal[6]': {
            value: 'var(--mantine-color-teal-6)',
          },
          'teal[7]': {
            value: 'var(--mantine-color-teal-7)',
          },
          'teal[8]': {
            value: 'var(--mantine-color-teal-8)',
          },
          'teal[9]': {
            value: 'var(--mantine-color-teal-9)',
          },
          'teal.filled': {
            value: 'var(--mantine-color-teal-filled)',
          },
          'teal.filledHover': {
            value: 'var(--mantine-color-teal-filled-hover)',
          },
          'teal.light': {
            value: 'var(--mantine-color-teal-light)',
          },
          'teal.lightHover': {
            value: 'var(--mantine-color-teal-light-hover)',
          },
          'teal.lightColor': {
            value: 'var(--mantine-color-teal-light-color)',
          },
          'teal.outline': {
            value: 'var(--mantine-color-teal-outline)',
          },
          'teal.outlineHover': {
            value: 'var(--mantine-color-teal-outline-hover)',
          },
          teal: {
            value: 'var(--mantine-color-teal-6)',
          },
          'red[0]': {
            value: 'var(--mantine-color-red-0)',
          },
          'red[1]': {
            value: 'var(--mantine-color-red-1)',
          },
          'red[2]': {
            value: 'var(--mantine-color-red-2)',
          },
          'red[3]': {
            value: 'var(--mantine-color-red-3)',
          },
          'red[4]': {
            value: 'var(--mantine-color-red-4)',
          },
          'red[5]': {
            value: 'var(--mantine-color-red-5)',
          },
          'red[6]': {
            value: 'var(--mantine-color-red-6)',
          },
          'red[7]': {
            value: 'var(--mantine-color-red-7)',
          },
          'red[8]': {
            value: 'var(--mantine-color-red-8)',
          },
          'red[9]': {
            value: 'var(--mantine-color-red-9)',
          },
          'red.filled': {
            value: 'var(--mantine-color-red-filled)',
          },
          'red.filledHover': {
            value: 'var(--mantine-color-red-filled-hover)',
          },
          'red.light': {
            value: 'var(--mantine-color-red-light)',
          },
          'red.lightHover': {
            value: 'var(--mantine-color-red-light-hover)',
          },
          'red.lightColor': {
            value: 'var(--mantine-color-red-light-color)',
          },
          'red.outline': {
            value: 'var(--mantine-color-red-outline)',
          },
          'red.outlineHover': {
            value: 'var(--mantine-color-red-outline-hover)',
          },
          red: {
            value: 'var(--mantine-color-red-6)',
          },
          'green[0]': {
            value: 'var(--mantine-color-green-0)',
          },
          'green[1]': {
            value: 'var(--mantine-color-green-1)',
          },
          'green[2]': {
            value: 'var(--mantine-color-green-2)',
          },
          'green[3]': {
            value: 'var(--mantine-color-green-3)',
          },
          'green[4]': {
            value: 'var(--mantine-color-green-4)',
          },
          'green[5]': {
            value: 'var(--mantine-color-green-5)',
          },
          'green[6]': {
            value: 'var(--mantine-color-green-6)',
          },
          'green[7]': {
            value: 'var(--mantine-color-green-7)',
          },
          'green[8]': {
            value: 'var(--mantine-color-green-8)',
          },
          'green[9]': {
            value: 'var(--mantine-color-green-9)',
          },
          'green.filled': {
            value: 'var(--mantine-color-green-filled)',
          },
          'green.filledHover': {
            value: 'var(--mantine-color-green-filled-hover)',
          },
          'green.light': {
            value: 'var(--mantine-color-green-light)',
          },
          'green.lightHover': {
            value: 'var(--mantine-color-green-light-hover)',
          },
          'green.lightColor': {
            value: 'var(--mantine-color-green-light-color)',
          },
          'green.outline': {
            value: 'var(--mantine-color-green-outline)',
          },
          'green.outlineHover': {
            value: 'var(--mantine-color-green-outline-hover)',
          },
          green: {
            value: 'var(--mantine-color-green-6)',
          },
          'yellow[0]': {
            value: 'var(--mantine-color-yellow-0)',
          },
          'yellow[1]': {
            value: 'var(--mantine-color-yellow-1)',
          },
          'yellow[2]': {
            value: 'var(--mantine-color-yellow-2)',
          },
          'yellow[3]': {
            value: 'var(--mantine-color-yellow-3)',
          },
          'yellow[4]': {
            value: 'var(--mantine-color-yellow-4)',
          },
          'yellow[5]': {
            value: 'var(--mantine-color-yellow-5)',
          },
          'yellow[6]': {
            value: 'var(--mantine-color-yellow-6)',
          },
          'yellow[7]': {
            value: 'var(--mantine-color-yellow-7)',
          },
          'yellow[8]': {
            value: 'var(--mantine-color-yellow-8)',
          },
          'yellow[9]': {
            value: 'var(--mantine-color-yellow-9)',
          },
          'yellow.filled': {
            value: 'var(--mantine-color-yellow-filled)',
          },
          'yellow.filledHover': {
            value: 'var(--mantine-color-yellow-filled-hover)',
          },
          'yellow.light': {
            value: 'var(--mantine-color-yellow-light)',
          },
          'yellow.lightHover': {
            value: 'var(--mantine-color-yellow-light-hover)',
          },
          'yellow.lightColor': {
            value: 'var(--mantine-color-yellow-light-color)',
          },
          'yellow.outline': {
            value: 'var(--mantine-color-yellow-outline)',
          },
          'yellow.outlineHover': {
            value: 'var(--mantine-color-yellow-outline-hover)',
          },
          yellow: {
            value: 'var(--mantine-color-yellow-6)',
          },
        },
      },
      likec4: {
        mixStrokeFill: {
          description: 'Mix of stroke and fill colors, used for "darker" areas',
          value: 'color-mix(in srgb, {colors.likec4.element.stroke} 90%, {colors.likec4.element.fill})',
        },
      },
    },
  },
  textStyles: {
    xs: {
      value: {
        fontSize: '0.75rem',
        lineHeight: '1rem',
      },
    },
    sm: {
      value: {
        fontSize: '0.875rem',
        lineHeight: '1.25rem',
      },
    },
    md: {
      value: {
        fontSize: '1rem',
        lineHeight: '1.5rem',
      },
    },
    lg: {
      value: {
        fontSize: '1.125rem',
        lineHeight: '1.75rem',
      },
    },
    xl: {
      value: {
        fontSize: '1.25rem',
        lineHeight: '1.75rem',
      },
    },
    '2xl': {
      value: {
        fontSize: '1.5rem',
        lineHeight: '2rem',
      },
    },
    '3xl': {
      value: {
        fontSize: '1.875rem',
        lineHeight: '2.25rem',
      },
    },
    '4xl': {
      value: {
        fontSize: '2.25rem',
        lineHeight: '2.5rem',
      },
    },
    '5xl': {
      value: {
        fontSize: '3rem',
        lineHeight: '1',
      },
    },
    '6xl': {
      value: {
        fontSize: '3.75rem',
        lineHeight: '1',
      },
    },
    '7xl': {
      value: {
        fontSize: '4.5rem',
        lineHeight: '1',
      },
    },
    '8xl': {
      value: {
        fontSize: '6rem',
        lineHeight: '1',
      },
    },
    '9xl': {
      value: {
        fontSize: '8rem',
        lineHeight: '1',
      },
    },
  },
  containerSizes: {
    xs: '320px',
    sm: '384px',
    md: '448px',
    lg: '512px',
    xl: '576px',
    '2xl': '672px',
    '3xl': '768px',
    '4xl': '896px',
    '5xl': '1024px',
    '6xl': '1152px',
    '7xl': '1280px',
    '8xl': '1440px',
  },
  semanticTokens: {
    colors: {
      likec4: {
        background: {
          DEFAULT: {
            description: 'Background color',
            value: {
              base: '{colors.mantine.colors.body}',
            },
          },
          pattern: {
            description: 'Background pattern color',
            value: {
              base: '{colors.mantine.colors.gray[4]}',
              _dark: '{colors.mantine.colors.dark[5]}',
            },
          },
        },
        element: {
          fill: {
            description: 'Element fill color',
            value: {
              base: '#3b82f6',
            },
          },
          stroke: {
            description: 'Element stroke color',
            value: {
              base: '#2563eb',
            },
          },
          hiContrast: {
            description: 'Element hiContrast text color (title)',
            value: {
              base: '#eff6ff',
              _likec4ColorAmber: '#FFE0C2',
              _likec4ColorBlue: '#eff6ff',
              _likec4ColorGray: '#fafafa',
              _likec4ColorSlate: '#f8fafc',
              _likec4ColorGreen: '#f8fafc',
              _likec4ColorIndigo: '#eef2ff',
              _likec4ColorMuted: '#f8fafc',
              _likec4ColorPrimary: '#eff6ff',
              _likec4ColorRed: '#FBD3CB',
              _likec4ColorSecondary: '#f0f9ff',
              _likec4ColorSky: '#f0f9ff',
            },
          },
          loContrast: {
            description: 'Element loContrast text color (description)',
            value: {
              base: '#bfdbfe',
              _likec4ColorAmber: '#f9b27c',
              _likec4ColorBlue: '#bfdbfe',
              _likec4ColorGray: '#d4d4d4',
              _likec4ColorSlate: '#cbd5e1',
              _likec4ColorGreen: '#c2f0c2',
              _likec4ColorIndigo: '#c7d2fe',
              _likec4ColorMuted: '#cbd5e1',
              _likec4ColorPrimary: '#bfdbfe',
              _likec4ColorRed: '#f5b2a3',
              _likec4ColorSecondary: '#B6ECF7',
              _likec4ColorSky: '#B6ECF7',
            },
          },
        },
        compound: {
          title: {
            description: 'Compound title color',
            value: {
              base: '{colors.likec4.element.loContrast}',
            },
          },
        },
        relation: {
          line: {
            description: 'Relationship line color',
            value: {
              base: '#6E6E6E',
              _likec4ColorAmber: '#b45309',
              _likec4ColorBlue: '#3b82f6',
              _likec4ColorGray: '#6E6E6E',
              _likec4ColorSlate: '#64748b',
              _likec4ColorGreen: '#15803d',
              _likec4ColorIndigo: '#6366f1',
              _likec4ColorMuted: '#64748b',
              _likec4ColorPrimary: '#3b82f6',
              _likec4ColorRed: '#AC4D39',
              _likec4ColorSecondary: '#0ea5e9',
              _likec4ColorSky: '#0ea5e9',
            },
          },
          label: {
            DEFAULT: {
              description: 'Relationship label color',
              value: {
                base: '#C6C6C6',
                _likec4ColorAmber: '#FFE0C2',
                _likec4ColorBlue: '#60a5fa',
                _likec4ColorGray: '#C6C6C6',
                _likec4ColorSlate: '#cbd5e1',
                _likec4ColorGreen: '#22c55e',
                _likec4ColorIndigo: '#818cf8',
                _likec4ColorMuted: '#cbd5e1',
                _likec4ColorPrimary: '#60a5fa',
                _likec4ColorRed: '#f5b2a3',
                _likec4ColorSecondary: '#38bdf8',
                _likec4ColorSky: '#38bdf8',
              },
            },
            bg: {
              description: 'Relationship label background color',
              value: {
                base: '#18191b',
                _likec4ColorAmber: '#78350f',
                _likec4ColorBlue: '#172554',
                _likec4ColorGray: '#18191b',
                _likec4ColorSlate: '#0f172a',
                _likec4ColorGreen: '#052e16',
                _likec4ColorIndigo: '#1e1b4b',
                _likec4ColorMuted: '#0f172a',
                _likec4ColorPrimary: '#172554',
                _likec4ColorRed: '#b91c1c',
                _likec4ColorSecondary: '#082f49',
                _likec4ColorSky: '#082f49',
              },
            },
          },
        },
      },
    },
  },
}
