name = "playground"
main = "./worker/index.ts"
compatibility_date = "2025-02-24"
compatibility_flags = [ "nodejs_compat_v2" ]
workers_dev = true

assets = { not_found_handling = "single-page-application", binding = "ASSETS" }

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "KV"
id = "23249b2617cc4a22a589bf934b0afa96"

[observability]
enabled = true
head_sampling_rate = 1
logs = { enabled = true, invocation_logs = true }

[env.production]
route = { pattern = "playground.likec4.dev", custom_domain = true }
kv_namespaces = [
  { binding = "KV", id = "ebf54cfa797b4d76bd08e83bb7214898", preview_id = "23249b2617cc4a22a589bf934b0afa96"}
]
