/* eslint-disable */
// DO NOT EDIT MANUALLY
// Auto-generated by
//  $ yarn generate

import LikeC4ViewStory from '../likec4/LikeC4ViewStory'

export const themecolorprimary = () => <LikeC4ViewStory viewId='themecolor_primary' />
themecolorprimary.storyName = 'primary'

export const themecolorblue = () => <LikeC4ViewStory viewId='themecolor_blue' />
themecolorblue.storyName = 'blue'

export const themecolorsecondary = () => <LikeC4ViewStory viewId='themecolor_secondary' />
themecolorsecondary.storyName = 'secondary'

export const themecolorsky = () => <LikeC4ViewStory viewId='themecolor_sky' />
themecolorsky.storyName = 'sky'

export const themecolormuted = () => <LikeC4ViewStory viewId='themecolor_muted' />
themecolormuted.storyName = 'muted'

export const themecolorslate = () => <LikeC4ViewStory viewId='themecolor_slate' />
themecolorslate.storyName = 'slate'

export const themecolorgray = () => <LikeC4ViewStory viewId='themecolor_gray' />
themecolorgray.storyName = 'gray'

export const themecolorred = () => <LikeC4ViewStory viewId='themecolor_red' />
themecolorred.storyName = 'red'

export const themecolorgreen = () => <LikeC4ViewStory viewId='themecolor_green' />
themecolorgreen.storyName = 'green'

export const themecoloramber = () => <LikeC4ViewStory viewId='themecolor_amber' />
themecoloramber.storyName = 'amber'

export const themecolorindigo = () => <LikeC4ViewStory viewId='themecolor_indigo' />
themecolorindigo.storyName = 'indigo'
