"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useUpdateEffect = exports.useSetState = exports.useLikeC4Styles = exports.useLikeC4ProjectsContext = exports.useLikeC4Projects = exports.useLikeC4ProjectId = exports.useLikeC4Project = exports.useHasProjects = exports.useOptionalLikeC4Model = exports.useLikeC4ViewModel = exports.useLikeC4Specification = exports.useLikeC4Model = exports.useOptionalCurrentViewModel = exports.useCurrentViewModel = exports.useOnDiagramEvent = exports.useDiagramContext = exports.useDiagramActorRef = exports.useDiagram = exports.useCurrentViewId = exports.useCurrentView = exports.useEnabledFeatures = exports.useDiagramEventHandlers = void 0;
var DiagramEventHandlers_1 = require("../context/DiagramEventHandlers");
Object.defineProperty(exports, "useDiagramEventHandlers", { enumerable: true, get: function () { return DiagramEventHandlers_1.useDiagramEventHandlers; } });
var DiagramFeatures_1 = require("../context/DiagramFeatures");
Object.defineProperty(exports, "useEnabledFeatures", { enumerable: true, get: function () { return DiagramFeatures_1.useEnabledFeatures; } });
var useCurrentView_1 = require("../hooks/useCurrentView");
Object.defineProperty(exports, "useCurrentView", { enumerable: true, get: function () { return useCurrentView_1.useCurrentView; } });
Object.defineProperty(exports, "useCurrentViewId", { enumerable: true, get: function () { return useCurrentView_1.useCurrentViewId; } });
var useDiagram_1 = require("../hooks/useDiagram");
Object.defineProperty(exports, "useDiagram", { enumerable: true, get: function () { return useDiagram_1.useDiagram; } });
Object.defineProperty(exports, "useDiagramActorRef", { enumerable: true, get: function () { return useDiagram_1.useDiagramActorRef; } });
Object.defineProperty(exports, "useDiagramContext", { enumerable: true, get: function () { return useDiagram_1.useDiagramContext; } });
Object.defineProperty(exports, "useOnDiagramEvent", { enumerable: true, get: function () { return useDiagram_1.useOnDiagramEvent; } });
var useCurrentViewModel_1 = require("../hooks/useCurrentViewModel");
Object.defineProperty(exports, "useCurrentViewModel", { enumerable: true, get: function () { return useCurrentViewModel_1.useCurrentViewModel; } });
Object.defineProperty(exports, "useOptionalCurrentViewModel", { enumerable: true, get: function () { return useCurrentViewModel_1.useOptionalCurrentViewModel; } });
var useLikeC4Model_1 = require("../hooks/useLikeC4Model");
Object.defineProperty(exports, "useLikeC4Model", { enumerable: true, get: function () { return useLikeC4Model_1.useLikeC4Model; } });
Object.defineProperty(exports, "useLikeC4Specification", { enumerable: true, get: function () { return useLikeC4Model_1.useLikeC4Specification; } });
Object.defineProperty(exports, "useLikeC4ViewModel", { enumerable: true, get: function () { return useLikeC4Model_1.useLikeC4ViewModel; } });
Object.defineProperty(exports, "useOptionalLikeC4Model", { enumerable: true, get: function () { return useLikeC4Model_1.useOptionalLikeC4Model; } });
var useLikeC4Project_1 = require("../hooks/useLikeC4Project");
Object.defineProperty(exports, "useHasProjects", { enumerable: true, get: function () { return useLikeC4Project_1.useHasProjects; } });
Object.defineProperty(exports, "useLikeC4Project", { enumerable: true, get: function () { return useLikeC4Project_1.useLikeC4Project; } });
Object.defineProperty(exports, "useLikeC4ProjectId", { enumerable: true, get: function () { return useLikeC4Project_1.useLikeC4ProjectId; } });
Object.defineProperty(exports, "useLikeC4Projects", { enumerable: true, get: function () { return useLikeC4Project_1.useLikeC4Projects; } });
Object.defineProperty(exports, "useLikeC4ProjectsContext", { enumerable: true, get: function () { return useLikeC4Project_1.useLikeC4ProjectsContext; } });
var useLikeC4Styles_1 = require("../hooks/useLikeC4Styles");
Object.defineProperty(exports, "useLikeC4Styles", { enumerable: true, get: function () { return useLikeC4Styles_1.useLikeC4Styles; } });
var useSetState_1 = require("../hooks/useSetState");
Object.defineProperty(exports, "useSetState", { enumerable: true, get: function () { return useSetState_1.useSetState; } });
var useUpdateEffect_1 = require("../hooks/useUpdateEffect");
Object.defineProperty(exports, "useUpdateEffect", { enumerable: true, get: function () { return useUpdateEffect_1.useUpdateEffect; } });
