import type { LayoutedView, LikeC4ViewModel } from 'likec4/model'
import { expectTypeOf, test } from 'vitest'
import { likec4model } from './likec4-model'

test('Model Codegen with valid types', () => {
  const m1 = likec4model
  expectTypeOf(m1.stage).toEqualTypeOf<'layouted'>()
  type A = typeof m1.Aux
  expectTypeOf<A['ElementId']>().toEqualTypeOf<
    | 'amazon'
    | 'cloud'
    | 'customer'
    | 'amazon.lambdas'
    | 'amazon.rds'
    | 'amazon.sqs'
    | 'cloud.legacy'
    | 'cloud.next'
    | 'cloud.supportUser'
    | 'cloud.ui'
    | 'amazon.lambdas.fn_enrich'
    | 'amazon.rds.aurora'
    | 'amazon.rds.pg'
    | 'amazon.sqs.queue1'
    | 'amazon.sqs.queue2'
    | 'amazon.s3'
    | 'amazon.s3.bucket1'
    | 'amazon.s3.bucket2'
    | 'cloud.legacy.backend'
    | 'cloud.next.backend'
    | 'cloud.next.events'
    | 'cloud.next.graphql'
    | 'cloud.ui.dashboard'
    | 'cloud.ui.mobile'
    | 'cloud.ui.supportPanel'
    | 'amazon.rds.aurora.tblUsers'
    | 'amazon.rds.pg.tblUsers'
    | 'cloud.legacy.backend.services'
    | 'cloud.next.graphql.myAccount'
    | 'cloud.next.graphql.updateAccount'
  >()

  expectTypeOf<A['DeploymentId']>().toEqualTypeOf<
    | 'customernd'
    | 'prod'
    | 'customernd.customer'
    | 'prod.eu'
    | 'prod.us'
    | 'prod.eu.backend'
    | 'prod.eu.zone1'
    | 'prod.eu.zone2'
    | 'prod.us.backend'
    | 'prod.us.zone1'
    | 'prod.us.zone2'
    | 'prod.eu.zone1.graphql'
    | 'prod.eu.zone1.ui'
    | 'prod.eu.zone2.graphql'
    | 'prod.eu.zone2.ui'
    | 'prod.us.zone1.graphql'
    | 'prod.us.zone1.ui'
    | 'prod.us.zone2.graphql'
    | 'prod.us.zone2.ui'
  >()

  expectTypeOf<A['ViewId']>().toEqualTypeOf<
    | 'amazon'
    | 'amazon_lambdas'
    | 'amazon_rds'
    | 'amazon_sqs'
    | 'amazon_s3'
    | 'backend'
    | 'cloud'
    | 'cloud_legacy'
    | 'cloud_legacy_backend'
    | 'cloud_next'
    | 'cloud_ui'
    | 'cloud_ui_dashboard'
    | 'cloud_ui_supportPanel'
    | 'cloud-to-amazon'
    | 'customer'
    | 'deploy_1'
    | 'dynamic-view-1'
    | 'graphql'
    | 'index'
    | 'mobile'
    | 'view-with-custom-colors'
  >()
  expectTypeOf(m1.view('cloud-to-amazon')).toEqualTypeOf<LikeC4ViewModel<A, LayoutedView<A>>>()
})
