import { viteConfig } from '@/vite/config'
import { viteWebcomponentConfig } from '@/vite/webcomponent'
import { copyFileSync, existsSync } from 'node:fs'
import { mkdtemp, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { build } from 'vite'
import type { LikeC4ViteConfig } from './config'

export async function mkTempPublicDir() {
  const publicDir = await mkdtemp(join(tmpdir(), '.likec4-public-'))
  await writeFile(join(publicDir, 'likec4-views.js'), '// generated by likec4\n')
  return publicDir
}

export const viteBuild = async (cfg?: LikeC4ViteConfig) => {
  const { isDev, ...config } = await viteConfig(cfg)

  const publicDir = await mkTempPublicDir()

  const webcomponentConfig = await viteWebcomponentConfig({
    languageServices: config.languageServices,
    outDir: publicDir,
    base: config.base
  })
  await build(webcomponentConfig)

  // Static website
  await build({
    ...config,
    publicDir,
    mode: 'production'
  })

  // Copy index.html to 404.html
  const indexHtml = resolve(config.build.outDir, 'index.html')
  if (existsSync(indexHtml)) {
    copyFileSync(
      indexHtml,
      resolve(config.build.outDir, '404.html')
    )
  }
}
