import { generateMarkdown } from '@likec4/generators'
import { fromWorkspace } from '@likec4/language-services/node'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import k from 'tinyrainbow'
import type { Argv } from 'yargs'
import { type ViteLogger, createLikeC4Logger, startTimer } from '../../../logger'
import { type UnknownLayouted, LikeC4Model } from '../../../model'
import { path, project, useDotBin } from '../../options'

const ERR_PROJECT_NOT_FOUND = 'project not found'

export const GENERATED_MARKER = '<!-- Generated by likec4 export markdown. Do not edit manually. -->'

export type MarkdownExportArgs = {
  path: string
  project: string | undefined
  useDot: boolean
  force?: boolean
}

function hasAuthoredViews(model: LikeC4Model<UnknownLayouted>): boolean {
  for (const view of model.views()) {
    if (view.$view.sourcePath !== undefined) return true
  }
  return false
}

function projectDescription(metadata: Record<string, unknown> | undefined): string | undefined {
  const description = metadata?.['description']
  return typeof description === 'string' ? description : undefined
}

async function canWrite(outfile: string, force: boolean): Promise<boolean> {
  if (force) return true
  let existing: string
  try {
    existing = await readFile(outfile, 'utf-8')
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return true
    throw error
  }
  return existing.startsWith(GENERATED_MARKER)
}

export async function runExportMarkdown(args: MarkdownExportArgs, logger: ViteLogger): Promise<void> {
  const timer = startTimer(logger)
  await using likec4 = await fromWorkspace(args.path, {
    graphviz: args.useDot ? 'binary' : 'wasm',
    watch: false,
  })

  let projects = [...likec4.languageServices.projects()]
  if (args.project) {
    projects = projects.filter(p => p.id === args.project)
    if (projects.length === 0) {
      logger.error(`${ERR_PROJECT_NOT_FOUND}: ${args.project}`)
      throw new Error(`${ERR_PROJECT_NOT_FOUND}: ${args.project}`)
    }
  } else {
    logger.info(`${k.dim('workspace:')} Found ${projects.length} projects`)
  }

  let written = 0
  for (const prj of projects) {
    const model = await likec4.layoutedModel(prj.id)
    if (model === LikeC4Model.EMPTY || !hasAuthoredViews(model)) {
      logger.warn(k.yellow(`Project ${prj.id} has no views, skipping`))
      continue
    }
    const outfile = join(prj.folder.fsPath, 'README.md')
    if (!(await canWrite(outfile, !!args.force))) {
      logger.warn(
        k.yellow(
          `${outfile} already exists and was not generated by this command, skipping (pass --force to overwrite)`,
        ),
      )
      continue
    }
    const description = projectDescription(prj.config.metadata)
    const content = generateMarkdown(model, description !== undefined ? { description } : {})
    await writeFile(outfile, `${GENERATED_MARKER}\n\n${content}`)
    written++
    logger.info(`${k.dim('generated')} ${outfile}`)
  }

  if (written === 0) {
    throw new Error('No documents generated; all projects were skipped')
  }
  timer.stopAndLog(`✓ export in `)
}

export function markdownCmd(yargs: Argv) {
  return yargs.command({
    command: 'markdown [path]',
    describe: 'export project(s) to README.md in each project folder',
    builder: yargs =>
      yargs
        .positional('path', path)
        .options({
          project,
          'use-dot': useDotBin,
          force: {
            type: 'boolean',
            desc: 'overwrite an existing README.md even if it was not generated by this command',
          },
        })
        .epilog(`${k.bold('Examples:')}
  ${k.green('$0 export markdown')}
    ${k.gray('Render every project to README.md in its own project folder')}

  ${k.green('$0 export markdown -p my-project src/likec4')}
    ${k.gray('Render only my-project to its README.md under src/likec4')}
`),
    handler: async args => {
      const logger = createLikeC4Logger('c4:export')
      await runExportMarkdown(
        {
          path: args.path,
          project: args.project,
          useDot: !!args['use-dot'],
          force: !!args.force,
        },
        logger,
      )
    },
  })
}
