import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

import { fileURLToPath } from 'node:url'
import { LikeC4Views } from '../src/likec4/generated'

const __dirname = dirname(fileURLToPath(import.meta.url))

const views = Object.keys(LikeC4Views)

function viewOf(viewId: string, storyName = viewId) {
  const name = viewId.replace('_', '')
  return `
export const ${name} = () => (
  <LikeC4ViewStory viewId="${viewId}" />
)
${name}.storyName = "${storyName}"
`
}

let out = resolve(__dirname, '../src/e2e/e2e--theme-colors.stories.tsx')

writeFileSync(
  out,
  `/* eslint-disable */
// DO NOT EDIT MANUALLY
// Auto-generated by
//  $ yarn generate

import LikeC4ViewStory from '../likec4/LikeC4ViewStory'

${
    views
      .filter(v => v !== 'themecolors' && v.startsWith('themecolor'))
      .map(v => viewOf(v, v.substring(11)))
      .join('\n')
  }
`
)

console.log(`Generated ${out}`)
