import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

import { LikeC4Views } from '../src/likec4/likec4.generated'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const views = Object.keys(LikeC4Views)

function viewOf(viewId, storyName = viewId) {
  const name = viewId.replace('_', '')
  return `
export const ${name} = () => (
  <LikeC4ViewStory viewId="${viewId}" />
)
${name}.storyName = "${storyName}"
`
}

let out = resolve(__dirname, '../src/e2e/e2e--theme-colors.stories.tsx')

writeFileSync(
  out,
  `/* eslint-disable */
// DO NOT EDIT MANUALLY
// Auto-generated by
//  $ yarn generate

import LikeC4ViewStory from '../likec4/LikeC4ViewStory'

${views
  .filter(v => v !== 'themecolors' && v.startsWith('themecolor'))
  .map(v => viewOf(v, v.substring(11)))
  .join('\n')}
`
)

console.log(`Generated ${out}`)
