"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@mantine/core");
var vanilla_extract_1 = require("@mantine/vanilla-extract");
var json5_1 = require("json5");
var node_fs_1 = require("node:fs");
var remeda_1 = require("remeda");
var mantineVars = (0, vanilla_extract_1.themeToVars)({});
var mapcolorToVar = function (color) {
    var _a;
    return (_a = {},
        _a[color] = {
            value: mantineVars.colors[color],
        },
        _a);
};
var mapcolors = function (colorkey, prefix) {
    var _a;
    if (prefix === void 0) { prefix = colorkey; }
    var color = mantineVars.colors[colorkey];
    return (__assign((_a = {}, _a[prefix] = {
        DEFAULT: {
            description: "Mantine color ".concat(colorkey),
            value: color[6],
        },
        filled: {
            description: "Mantine color ".concat(colorkey, " filled"),
            value: color.filled,
        },
        filledHover: {
            description: "Mantine color ".concat(colorkey, " filled hover"),
            value: color.filledHover,
        },
        light: {
            description: "Mantine color ".concat(colorkey, " light"),
            value: color.light,
        },
        lightHover: {
            description: "Mantine color ".concat(colorkey, " light hover"),
            value: color.lightHover,
        },
        lightColor: {
            description: "Mantine color ".concat(colorkey, " light color"),
            value: color.lightColor,
        },
        outline: {
            description: "Mantine color ".concat(colorkey, " outline"),
            value: color.outline,
        },
        outlineHover: {
            description: "Mantine color ".concat(colorkey, " outline hover"),
            value: color.outlineHover,
        },
    }, _a), (0, remeda_1.mapToObj)((0, remeda_1.range)(0, 10), function (idx) { return [
        "".concat(prefix, "[").concat(idx, "]"),
        {
            description: "Mantine color ".concat(colorkey, ".").concat(idx),
            // @ts-ignore
            value: color[idx],
        },
    ]; })));
};
var tokens = {
    colors: {
        mantine: {
            colors: __assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign(__assign({}, mapcolors('primaryColors', 'primary')), mapcolorToVar('white')), mapcolorToVar('text')), mapcolorToVar('body')), mapcolorToVar('dimmed')), mapcolorToVar('defaultBorder')), mapcolorToVar('defaultColor')), mapcolorToVar('defaultHover')), mapcolorToVar('default')), mapcolorToVar('error')), mapcolorToVar('placeholder')), mapcolors('gray')), mapcolors('dark')), mapcolors('orange')), mapcolors('teal')), mapcolors('red')), mapcolors('green')), mapcolors('yellow')),
        },
    },
};
var ts = "// This file is auto-generated by scripts/generate.ts\n\nexport const breakpoints = ".concat(json5_1.default.stringify(core_1.DEFAULT_THEME.breakpoints, null, 2), "\n\nexport const tokens = ").concat(json5_1.default.stringify(tokens, null, 2), "\n\nexport const mantine = ").concat(json5_1.default.stringify(mantineVars, null, 2), " as const\n");
(0, node_fs_1.writeFileSync)('./src/generated.ts', ts);
console.log('theme generated');
