import { DEFAULT_THEME } from '@mantine/core'
import { themeToVars } from '@mantine/vanilla-extract'
import type { Config } from '@pandacss/dev'
import JSON5 from 'json5'
import { writeFileSync } from 'node:fs'
import {
  mapToObj,
  mapValues,
  range,
} from 'remeda'
const mantineVars = themeToVars({})

// omitting stack her
type MantineColors = typeof mantineVars.colors
type MantineColorValues = typeof mantineVars.colors.primaryColors
type ExtendableTheme = NonNullable<Config['theme']>

const mapcolorToVar = <C extends keyof MantineColors>(color: C) => ({
  [color]: {
    value: mantineVars.colors[color] as string,
  },
} as {
  [key in C]: { value: string }
})

const mapcolors = (colorkey: keyof MantineColors, prefix = colorkey) => {
  const color = mantineVars.colors[colorkey] as MantineColorValues
  return ({
    [prefix]: {
      DEFAULT: {
        description: `Mantine color ${colorkey}`,
        value: color[6],
      },
      filled: {
        description: `Mantine color ${colorkey} filled`,
        value: color.filled,
      },
      filledHover: {
        description: `Mantine color ${colorkey} filled hover`,
        value: color.filledHover,
      },
      light: {
        description: `Mantine color ${colorkey} light`,
        value: color.light,
      },
      lightHover: {
        description: `Mantine color ${colorkey} light hover`,
        value: color.lightHover,
      },
      lightColor: {
        description: `Mantine color ${colorkey} light color`,
        value: color.lightColor,
      },
      outline: {
        description: `Mantine color ${colorkey} outline`,
        value: color.outline,
      },
      outlineHover: {
        description: `Mantine color ${colorkey} outline hover`,
        value: color.outlineHover,
      },
    },
    ...mapToObj(range(0, 10), idx => [
      `${prefix}[${idx}]`,
      {
        description: `Mantine color ${colorkey}.${idx}`,
        // @ts-ignore
        value: color[idx],
      },
    ]),
  })
}

const tokens = {
  fontSizes: {
    ...mapValues(DEFAULT_THEME.fontSizes, (value) => ({ value })),
  },
  lineHeights: {
    ...mapValues(DEFAULT_THEME.lineHeights, (value) => ({ value })),
  },
  colors: {
    mantine: {
      colors: {
        ...mapcolors('primaryColors', 'primary'),
        ...mapcolorToVar('white'),
        ...mapcolorToVar('text'),
        ...mapcolorToVar('body'),
        ...mapcolorToVar('dimmed'),
        ...mapcolorToVar('defaultBorder'),
        ...mapcolorToVar('defaultColor'),
        ...mapcolorToVar('defaultHover'),
        ...mapcolorToVar('default'),
        ...mapcolorToVar('error'),
        ...mapcolorToVar('placeholder'),
        ...mapcolors('gray'),
        ...mapcolors('dark'),
        ...mapcolors('orange'),
        ...mapcolors('teal'),
        ...mapcolors('red'),
        ...mapcolors('green'),
        ...mapcolors('yellow'),
      },
    },
  },
} satisfies ExtendableTheme['tokens']

const ts = `// This file is auto-generated by scripts/generate.ts

export const breakpoints = ${JSON5.stringify(DEFAULT_THEME.breakpoints, null, 2)}

export const tokens = ${JSON5.stringify(tokens, null, 2)}

export const mantine = ${JSON5.stringify(mantineVars, null, 2)} as const
`

writeFileSync('./src/generated.ts', ts)
console.log('theme generated')
