import { defineSlotRecipe } from '@pandacss/dev'

export const floatingWindow = defineSlotRecipe({
  className: 'likec4-floating-window',
  jsx: ['FloatingWindow', /FloatingWindow/],
  slots: ['root', 'header', 'content', 'resizeHandler'],
  description: 'LikeC4 Floating window',
  base: {
    root: {
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'stretch',
      position: 'fixed',
      paddingBlock: '4',
      paddingInline: '4',
      width: 'auto',
      height: 'auto',
      maxWidth: '100vw',
      maxHeight: '100vh',
      backgroundColor: 'likec4.panel.bg',
      border: '1px solid {colors.likec4.dropdown.border}',
      boxShadow: 'lg',
      borderRadius: 'md',
      zIndex: 'likec4.floatingWindow',
      pointerEvents: 'all',
      overflow: 'hidden',
    },
    header: {
      flex: '0',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      cursor: 'move',
      marginBlockStart: '-4',
      marginInline: '-4',
      paddingBlockStart: '2',
      paddingBlockEnd: '2',
      paddingInline: '4',
    },
    content: {
      flex: '1 1 100%',
      height: '100%',
      display: 'flex',
      overflow: 'hidden',
    },
    resizeHandler: {
      position: 'absolute',
      width: 'icon.sm',
      height: 'icon.sm',
      border: `default`,
      ['&[data-position="bottom-right"]']: {
        borderWidth: '2',
        borderColor: 'mantine.dark[3]',
        borderTop: 'none',
        borderLeft: 'none',
        borderBottomRightRadius: 'sm',
        bottom: '1',
        right: '1',
        cursor: 'se-resize',
        _hover: {
          borderWidth: '3',
          borderColor: 'mantine.dark[1]',
        },
      },
    },
  },
  variants: {
    state: {
      minimized: {},
      visible: {},
      hidden: {},
    },
  },
  defaultVariants: {
    state: 'visible',
  },
  staticCss: ['*'],
})
