/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WIdImport } from './routes/w.$id'
import { Route as WIdIndexImport } from './routes/w.$id.index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const WIdRoute = WIdImport.update({
  path: '/w/$id',
  getParentRoute: () => rootRoute
} as any)

const WIdIndexRoute = WIdIndexImport.update({
  path: '/',
  getParentRoute: () => WIdRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/w/$id': {
      preLoaderRoute: typeof WIdImport
      parentRoute: typeof rootRoute
    }
    '/w/$id/': {
      preLoaderRoute: typeof WIdIndexImport
      parentRoute: typeof WIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WIdRoute.addChildren([WIdIndexRoute])
])

/* prettier-ignore-end */
