/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as RedirectAfterAuthImport } from './routes/redirect-after-auth';
import { Route as IndexImport } from './routes/index';
import { Route as WWorkspaceIdRouteImport } from './routes/w.$workspaceId/route';
import { Route as WWorkspaceIdIndexImport } from './routes/w.$workspaceId/index';
import { Route as ShareShareIdIndexImport } from './routes/share.$shareId/index';
import { Route as WWorkspaceIdViewIdImport } from './routes/w.$workspaceId/$viewId';
import { Route as ShareShareIdNotFoundImport } from './routes/share.$shareId/not-found';
import { Route as ShareShareIdEnterPincodeImport } from './routes/share.$shareId/enter-pincode';
import { Route as ShareShareIdViewRouteImport } from './routes/share.$shareId/view/route';
import { Route as ShareShareIdViewViewIdImport } from './routes/share.$shareId/view/$viewId';
// Create/Update Routes
const RedirectAfterAuthRoute = RedirectAfterAuthImport.update({
    id: '/redirect-after-auth',
    path: '/redirect-after-auth',
    getParentRoute: () => rootRoute,
});
const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
});
const WWorkspaceIdRouteRoute = WWorkspaceIdRouteImport.update({
    id: '/w/$workspaceId',
    path: '/w/$workspaceId',
    getParentRoute: () => rootRoute,
});
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WWorkspaceIdRouteRoute,
});
const ShareShareIdIndexRoute = ShareShareIdIndexImport.update({
    id: '/share/$shareId/',
    path: '/share/$shareId/',
    getParentRoute: () => rootRoute,
});
const WWorkspaceIdViewIdRoute = WWorkspaceIdViewIdImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => WWorkspaceIdRouteRoute,
});
const ShareShareIdNotFoundRoute = ShareShareIdNotFoundImport.update({
    id: '/share/$shareId/not-found',
    path: '/share/$shareId/not-found',
    getParentRoute: () => rootRoute,
});
const ShareShareIdEnterPincodeRoute = ShareShareIdEnterPincodeImport.update({
    id: '/share/$shareId/enter-pincode',
    path: '/share/$shareId/enter-pincode',
    getParentRoute: () => rootRoute,
});
const ShareShareIdViewRouteRoute = ShareShareIdViewRouteImport.update({
    id: '/share/$shareId/view',
    path: '/share/$shareId/view',
    getParentRoute: () => rootRoute,
});
const ShareShareIdViewViewIdRoute = ShareShareIdViewViewIdImport.update({
    id: '/$viewId',
    path: '/$viewId',
    getParentRoute: () => ShareShareIdViewRouteRoute,
});
const WWorkspaceIdRouteRouteChildren = {
    WWorkspaceIdViewIdRoute: WWorkspaceIdViewIdRoute,
    WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
};
const WWorkspaceIdRouteRouteWithChildren = WWorkspaceIdRouteRoute._addFileChildren(WWorkspaceIdRouteRouteChildren);
const ShareShareIdViewRouteRouteChildren = {
    ShareShareIdViewViewIdRoute: ShareShareIdViewViewIdRoute,
};
const ShareShareIdViewRouteRouteWithChildren = ShareShareIdViewRouteRoute._addFileChildren(ShareShareIdViewRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    RedirectAfterAuthRoute: RedirectAfterAuthRoute,
    WWorkspaceIdRouteRoute: WWorkspaceIdRouteRouteWithChildren,
    ShareShareIdViewRouteRoute: ShareShareIdViewRouteRouteWithChildren,
    ShareShareIdEnterPincodeRoute: ShareShareIdEnterPincodeRoute,
    ShareShareIdNotFoundRoute: ShareShareIdNotFoundRoute,
    ShareShareIdIndexRoute: ShareShareIdIndexRoute,
};
export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/redirect-after-auth",
        "/w/$workspaceId",
        "/share/$shareId/view",
        "/share/$shareId/enter-pincode",
        "/share/$shareId/not-found",
        "/share/$shareId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/redirect-after-auth": {
      "filePath": "redirect-after-auth.tsx"
    },
    "/w/$workspaceId": {
      "filePath": "w.$workspaceId/route.tsx",
      "children": [
        "/w/$workspaceId/$viewId",
        "/w/$workspaceId/"
      ]
    },
    "/share/$shareId/view": {
      "filePath": "share.$shareId/view/route.tsx",
      "children": [
        "/share/$shareId/view/$viewId"
      ]
    },
    "/share/$shareId/enter-pincode": {
      "filePath": "share.$shareId/enter-pincode.tsx"
    },
    "/share/$shareId/not-found": {
      "filePath": "share.$shareId/not-found.tsx"
    },
    "/w/$workspaceId/$viewId": {
      "filePath": "w.$workspaceId/$viewId.tsx",
      "parent": "/w/$workspaceId"
    },
    "/share/$shareId/": {
      "filePath": "share.$shareId/index.tsx"
    },
    "/w/$workspaceId/": {
      "filePath": "w.$workspaceId/index.tsx",
      "parent": "/w/$workspaceId"
    },
    "/share/$shareId/view/$viewId": {
      "filePath": "share.$shareId/view/$viewId.tsx",
      "parent": "/share/$shareId/view"
    }
  }
}
ROUTE_MANIFEST_END */
