/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WorkspaceIdImport } from './routes/workspace.$id'
import { Route as WorkspaceIdIndexImport } from './routes/workspace.$id.index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const WorkspaceIdRoute = WorkspaceIdImport.update({
  path: '/workspace/$id',
  getParentRoute: () => rootRoute
} as any)

const WorkspaceIdIndexRoute = WorkspaceIdIndexImport.update({
  path: '/',
  getParentRoute: () => WorkspaceIdRoute
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/workspace/$id': {
      preLoaderRoute: typeof WorkspaceIdImport
      parentRoute: typeof rootRoute
    }
    '/workspace/$id/': {
      preLoaderRoute: typeof WorkspaceIdIndexImport
      parentRoute: typeof WorkspaceIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  WorkspaceIdRoute.addChildren([WorkspaceIdIndexRoute])
])

/* prettier-ignore-end */
