name: dependencies
on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  dependency-review:
    name: dependency review
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
