name: pull_request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  checks: read
  contents: read
  statuses: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build:
    name: Build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'releases/')"
    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: ./.github/actions/bootstrap

      - name: turborepo-cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build packages
        run: yarn build

      - name: Compile
        run: yarn compile:all

      - name: Test
        run: yarn test
