name: vscode

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to Marketplaces'
        type: boolean
        default: false
  push:
    tags:
      - 'v*'

permissions:
  actions: write
  contents: read

env:
  NODE_ENV: production
  CLOUDFLARE_ENV: production
  FORCE_COLOR: true
  DO_NOT_TRACK: '1'

jobs:
  publish-vscode:
    name: publish
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    if: ${{ github.repository_owner == 'likec4' }}
    steps:
      - uses: actions/checkout@v6

      - name: 🛠️ bootstrap
        uses: ./.github/actions/bootstrap

      - name: ⚙️ build
        working-directory: packages/vscode
        run: |
          pnpm turbo run build

      - name: 📦 package vsix
        working-directory: packages/vscode
        run: |
          pnpm package-vsix

      - name: 📦 upload vsix
        uses: actions/upload-artifact@v6
        with:
          name: likec4.vsix
          if-no-files-found: error
          path: packages/vscode/likec4.vsix

      - name: 🚀 publish vsce
        if: ${{ startsWith(github.ref, 'refs/tags/v') || inputs.publish }}
        run: |
          pnpx @vscode/vsce publish --skip-duplicate --packagePath likec4.vsix
        working-directory: packages/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: 🚀 publish open vsx
        if: ${{ startsWith(github.ref, 'refs/tags/v') || inputs.publish }}
        run: |
          pnpx ovsx publish --skip-duplicate likec4.vsix
        working-directory: packages/vscode
        env:
          OVSX_PAT: ${{ secrets.VSX_PAT }}
