import { fdir } from 'fdir'
import { mkdirSync, writeFileSync } from 'node:fs'
import { sep } from 'path'

const files = new fdir()
  .filter((name, isDir) => !isDir && name.endsWith('.tsx'))
  .withFullPaths()
  .crawl('../icons')
  .sync()
  .sort()

console.info(`Found ${files.length} files`)

let added = 0
const grouped = files.reduce((acc, path) => {
  const parts = path.split(sep)
  const icon = (parts.pop() || 'invalid').replace('.tsx', '')
  const group = parts.pop() || 'error'
  if (!['aws', 'azure', 'gcp', 'tech', 'bootstrap'].includes(group)) {
    console.error(`Unknown group ${group}`)
    return acc
  }
  added++
  acc[group as keyof typeof acc].push(icon)
  return acc
}, {
  aws: [] as string[],
  azure: [] as string[],
  gcp: [] as string[],
  tech: [] as string[],
  bootstrap: [] as string[],
})

const source = `// @ts-nocheck
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Generated from @likec4/icons
const icons = [...Object.entries({
  aws: ${JSON.stringify(grouped.aws)},
  azure: ${JSON.stringify(grouped.azure)},
  gcp: ${JSON.stringify(grouped.gcp)},
  tech: ${JSON.stringify(grouped.tech)},
  bootstrap: ${JSON.stringify(grouped.bootstrap)},
})]
  .flatMap(([group, names]) => names.map((name) => group + ':' + name))

export const LibIcons: string = [
  'likec4lib {',
  '  icons {',
  ...icons.map((icon) => '    ' + icon),
  '  }',
  '}',
].join('\\n')
`

mkdirSync('src/generated-lib', { recursive: true })
writeFileSync('src/generated-lib/icons.ts', source, 'utf-8')

console.info(`Generated src/generated-lib/icons.ts with`, added, `icons`)
