import { Icons } from '@likec4/icons/all'
import compareNatural from 'natural-compare-lite'
import { mkdirSync, writeFileSync } from 'node:fs'

const icons = Object.keys(Icons).sort(compareNatural).map((icon) => {
  const [group, name] = icon.split(':') as [string, string]
  return { group, name }
})

if (icons.length === 0) {
  console.error('No icons found')
  process.exit(1)
}

const grouped = icons.reduce((acc, icon) => {
  if (!acc[icon.group]) {
    acc[icon.group] = []
  }
  acc[icon.group]!.push(icon.name)
  return acc
}, {} as Record<string, string[]>)

const source = `// @ts-nocheck
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Generated from @likec4/icons
const icons = [...Object.entries(${JSON.stringify(grouped)})]
  .flatMap(([group, names]) => names.map((name) => group + ':' + name))

export const LibIcons: string = [
  'likec4lib {',
  '  icons {',
  ...icons.map((icon) => '    ' + icon),
  '  }',
  '}',
].join('\\n')
`

mkdirSync('src/generated-lib', { recursive: true })
writeFileSync('src/generated-lib/icons.ts', source, 'utf-8')

console.info(`Generated src/generated-lib/icons.ts with ${icons.length} icons`)
